.github/PULL_REQUEST_TEMPLATE.md, .grenrc.json, CHANGELOG.md, libs/packages/components/package.json, libs/packages/experimental/package.json, libs/packages/layouts/package.json, libs/packages/sam-formly/package.json, libs/packages/sam-material-extensions/package.json, package-lock.json, package.json
This PR adds support for gren (github-release-notes) and then combined scripts together to automate versioning and creating new releases.
This script automatically versions each library along with the main package, commits the update and adds a git tag, pushes the tag to github, creates a new release on github with notes, generates a changelog, and commits the changelog to the repo and pushes it to github.
There are no training wheels on this script -- when the script executes, it will make several commits related to updating the version and commiting the change log and push them to the master branch. If a mistake is made, it will require rolling back the commits, deleting the tags, and removing the release.
=> Automate Versioning And Release Notes

libs/component-sample/src/lib/feature/header-sample/header-sample.component.html, libs/packages/components/src/lib/header/header.component.html, libs/packages/components/src/lib/header/header.component.ts, libs/packages/components/src/lib/top-banner/top-banner.component.html, libs/packages/components/src/lib/top-banner/top-banner.component.ts
=> Added description for the top banner

libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
In order to place the "X" properly, you need to add a position attribute to one of the parents. Otherwise, the X floats outside of the container.
=> Position the "X" (clear button) within the input.

libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
=> Ensure the "X" button does not obstruct the text

libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html, libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts, libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts, libs/packages/components/src/lib/autocomplete-search/models/SDSAutocompleteConfiguration.ts, libs/packages/components/src/lib/autocomplete/autocomplete.component.html, libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts, package.json
=> Autocomplete tags

karma.conf.js, libs/packages/components/src/lib/external-link/external-link.directive.spec.ts
I wrote unit tests for the external link directive. I was able to get coverage for the statements and functions, but the branches are a bit trickier. The icons wouldn't render in the test suite, so instead of icons being created by the directive on the fake component, an empty array was created instead. Branch coverage remains at 50% for this reason.
https://cm-jira.usa.gov/browse/IAE-35332
- [ X] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [x ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [x ] My code passes the automated linter.
- [x ] I have added tests to cover my changes.
=> External links code coverage 35332

libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
Fix margin for multicheckboxes Closes IAE-40216 
Addresses margin issues flagged in https://github.com/GSA/sam-design-system/issues/317.
[Issue](https://github.com/GSA/sam-design-system/issues/317)
[Ticket](https://cm-jira.usa.gov/browse/IAE-40216)
=> bugfix(multicheckbox): styling fix

libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts, libs/packages/components/src/lib/key-helper/key-helper.ts
one of the problems with accessibility that the dropdown wasn't responding to the alt + down combination. JAWS would state that dropdown is open but it wouldn't actually open it.
Looking at the code it doesn't seem to like its meant to handle multiple keys at the same time, so maybe just binding it to alt key is a viable solution.?
=> Make the combo box pick up alt key

libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.component.html, libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.component.ts, libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.module.ts, libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.html, libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.ts, libs/documentation/src/lib/components/subheader/demos/search/subheader-search.module.ts, libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.component.html, libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.module.ts, libs/packages/components/src/lib/search/search.component.html, libs/packages/components/src/lib/search/search.component.ts, libs/packages/components/src/lib/search/search.spec.ts
Tweaks to the subheader demos were requested. Also it was raised that the seachbar staying expanded on tablet/mobile was not desired.
=> Fix subheader demos and searchbar blur

libs/documentation/src/lib/pages/layout/layout.component.ts
Github issue #427 - Update our demo to use Subject rather than BehaviorSubject so that an initial value of null is not emitted
=> Change behaviour subject to subject in filter demo

libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts, libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
Stems from github issue #387 and JIRA ticket https://cm-jira.usa.gov/browse/IAE-44006#. The changes here resolves two observed issues with single select autocomplete in sds-filters:
1. Upon refresh, when history is enabled, the autocomplete properly sets the data model based on url parameters, but does not update the UI with the proper values. As seen in image below, after refreshing, the data model is displaying the correct values based off url parameters, but those values are not reflected in the autocomplete inputs:
2. In the case when there are two auto-complete with the logic of second autocomplete being disabled until the value of first autocomplete is selected and the expectation that clearing out the first autocomplete form should clear the second as well, the data models for the …
=> Resolve autocomplete issues with history url and disabled expressions

libs/documentation/src/lib/components/formly/autocomplete/demos/disable/autocomplete-disable.component.ts
Our demo currently does not include conditional disable for autocomplete, so this PR modifies the demo for disabled autocomplete to use expression properties
https://github.com/GSA/sam-design-system/issues/387
- [ x ] New feature (non-breaking change which adds functionality) -> Apply enhancement label
=> Update demo to include disabled with expression properties

libs/documentation/src/lib/components/formly/search/demos/submit/search-handle-submit.component.html, libs/documentation/src/lib/components/formly/search/demos/submit/search-handle-submit.component.ts, libs/documentation/src/lib/components/formly/search/demos/submit/search-handle-submit.module.ts, libs/documentation/src/lib/components/formly/search/search.module.ts, libs/documentation/src/lib/components/search/demos/basic/search-basic.component.html, libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts, libs/packages/components/src/lib/search/search.component.html, libs/packages/components/src/lib/search/search.component.ts, libs/packages/components/src/lib/search/search.spec.ts, libs/packages/sam-formly/src/lib/formly/types/search.ts
Updated search component to update model as user is typing rather than only when submit button is clicked. 
**NOTE: This will cause modelChange event on the formly component to fire with each keystroke. Therefore it is no longer possible to use this event as an indication that user has submitted. For an indication user has submitted make use of the submitHandler field detailed in the documentation**
Added submit event which is triggered when user clicks submit button. This event will include the value for search, but not the rest of the formly model. The event can be binded to using the submitHandler field in templateOptions.
Additionally added formly documentation to highlight the change and document how to use added features. Updated non-formly documentation to note the change and added …
=> IAE-4429 Update search model writing behavior

libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
Fix adds check that changeDetectorRef is not destroyed before calling it to avoid #435.
https://cm-jira.usa.gov/browse/IAE-44578
Addresses #435.
When view is switched, and changeDetectorRef is destroyed, the formControl is still throwing valueChange events leading to the error detailed in the issue.
=> IAE-44578 Add check to ensure changeDetectorRef not destroyed

apps/sam-design-system-site/src/app/app.component.html, libs/documentation/src/lib/components/selection-panel/demos/basic-selection-panel/basic-selection-panel.component.html, libs/documentation/src/lib/components/selection-panel/demos/basic-selection-panel/basic-selection-panel.component.ts, libs/documentation/src/lib/components/selection-panel/demos/basic-selection-panel/basic-selection-panel.module.ts, libs/documentation/src/lib/components/selection-panel/navigation.config.ts, libs/documentation/src/lib/components/selection-panel/selection-panel.module.ts, libs/documentation/src/lib/documentation.module.ts
Extension of the side-toolbar PR - Create demo page for the selection panel component. Relies on CSS from https://github.com/GSA/sam-styles/pull/372.
=> Add selection panel to demo page

libs/packages/components/src/lib/public-api.ts
Merge conflict oversight  - truncate.text.module was exported twice
Remove duplicate export of truncate.text module
=> Remove duplicate export of truncate-text library

apps/sam-design-system-site/src/app/app.component.html, libs/documentation/src/lib/components/formly/readonly/demos/custom-template/custom-template.component.html, libs/documentation/src/lib/components/formly/readonly/demos/custom-template/custom-template.component.ts, libs/documentation/src/lib/components/formly/readonly/demos/custom-template/custom-template.module.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-basic/readonly-basic.component.html, libs/documentation/src/lib/components/formly/readonly/demos/readonly-basic/readonly-basic.component.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-basic/readonly-basic.module.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-formly-type/readonly-formly-type.component.html, libs/documentation/src/lib/components/formly/readonly/demos/readonly-formly-type/readonly-formly-type.component.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-formly-type/readonly-formly.module.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-wrapper/readonly-wrapper.component.html, libs/documentation/src/lib/components/formly/readonly/demos/readonly-wrapper/readonly-wrapper.component.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-wrapper/readonly-wrapper.module.ts, libs/documentation/src/lib/components/formly/readonly/readonly.module.ts, libs/documentation/src/lib/documentation.module.ts, libs/packages/sam-formly/src/lib/formly/formly.config.ts, libs/packages/sam-formly/src/lib/formly/formly.module.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly.module.ts, libs/packages/sam-formly/src/lib/formly/sds-formly-options.ts, libs/packages/sam-formly/src/lib/formly/services/formly-utils.service.ts, libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts, libs/packages/sam-formly/src/lib/formly/wrappers/readonly.wrapper.ts, libs/packages/sam-formly/src/lib/public-api.ts
This PR adds the readonly wrapper to formly configurations. It also adds a new formly type - readonly - utilizing the wrapper, which will permanently stay in readonly mode.
=> Add readonly wrapper to formly configuration

apps/sam-design-system-site/src/app/app.component.html, libs/documentation/src/lib/components/formly/readonly/demos/custom-template/custom-template.component.html, libs/documentation/src/lib/components/formly/readonly/demos/custom-template/custom-template.component.ts, libs/documentation/src/lib/components/formly/readonly/demos/custom-template/custom-template.module.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-basic/readonly-basic.component.html, libs/documentation/src/lib/components/formly/readonly/demos/readonly-basic/readonly-basic.component.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-basic/readonly-basic.module.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-formly-type/readonly-formly-type.component.html, libs/documentation/src/lib/components/formly/readonly/demos/readonly-formly-type/readonly-formly-type.component.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-formly-type/readonly-formly.module.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-wrapper/readonly-wrapper.component.html, libs/documentation/src/lib/components/formly/readonly/demos/readonly-wrapper/readonly-wrapper.component.ts, libs/documentation/src/lib/components/formly/readonly/demos/readonly-wrapper/readonly-wrapper.module.ts, libs/documentation/src/lib/components/formly/readonly/readonly.module.ts, libs/documentation/src/lib/documentation.module.ts, libs/packages/sam-formly/src/lib/formly/formly.config.ts, libs/packages/sam-formly/src/lib/formly/formly.module.ts, libs/packages/sam-formly/src/lib/formly/models/formly-types.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-container.component.html, libs/packages/sam-formly/src/lib/formly/readonly/readonly-container.component.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-options.model.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly.module.ts, libs/packages/sam-formly/src/lib/formly/sds-formly-options.ts, libs/packages/sam-formly/src/lib/formly/services/formly-utils.service.ts, libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts, libs/packages/sam-formly/src/lib/formly/wrappers/readonly.wrapper.ts, libs/packages/sam-formly/src/lib/public-api.ts
This PR is continuation from #460 - Adds the wrapper level component to consolidate each individual readonly types. The wrapper decides which readonly component to display based on the provided formly type. Also, updated to add enumeration for all formly types we support.
=> Add wrapper for formly readonly components

libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
Currently the sds filters only checks 1 level deep for value in filters when checking to determine whether those filters should be automatically visible or not. So for field configs with nested field groups, the filters were not automatically becoming visible despite having value. This change modifies the logic to add a recursive check through field groups when checking for filter model's value.
From github issue #477
=> Add recursive definition for fieldgroups in hide check for sds-filters

libs/documentation/src/lib/components/table/demos/full/full.component.html, libs/documentation/src/lib/components/table/demos/full/full.component.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-container.component.ts, libs/packages/sam-material-extensions/src/lib/table/table.component.html, libs/packages/sam-material-extensions/src/lib/table/table.component.ts
Allow users the ability to listen for and react to table expansion/collapse event.
This event gives users the option to dynamically load data on table item expansion rather than needing to eagerly load all the information.
=> Add output event on table expansion for Sds-table

libs/packages/components/src/lib/icon/icon.component.scss
The package that is being used to provide bootstrap icons updated to use the latest bootstrap icons. As a result, the existing icons were updated to have their width and height updated to be 16px rather than 1em as it was when these icons were initially pulled into SDS. Added styling to override this and ensure icons continue to have their height and width set at 1em so their size will scale properly.
https://cm-jira.usa.gov/browse/IAEDEV-45480
=> Update icon styling to ensure bootstrap icon size based on em not px

libs/documentation/src/lib/components/header/demos/basic/header-basic.component.ts, libs/documentation/src/lib/components/header/demos/header-alerts/header-alerts.component.ts, libs/documentation/src/lib/components/header/demos/header-hidden-logo/header-hidden-logo.component.ts
Update our term usage in header demo: Messages changed to Notifications
=> Update header demo to use word notifications

libs/packages/components/src/lib/autocomplete/autocomplete.component.ts, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Contains two fixes:
1. Unsubscribe from formly update communication service - Issue brought up through Search mfe - continuously navigating between search and saved search page was causing the number of api calls made to retrieve search results to increase.
2. Manually set disable state of internal autocomplete component - Another issue brought up through Search mfe, and mentioned by Kidany where using expression properties to toggle disabled state of autocomplete was not disabling the autocomplete input until another user event was given (ie click anywhere on page).
=> Resolve issue with autocomplete disable, unsubscribe on layout during onDestroy

libs/documentation/src/lib/components/icons/demos/stacking/icons-stacking.component.html, libs/documentation/src/lib/components/icons/demos/stacking/icons-stacking.component.ts, libs/documentation/src/lib/components/icons/demos/stacking/icons-stacking.module.ts, libs/documentation/src/lib/components/icons/icons.module.ts, libs/packages/components/src/lib/icon/icon.component.scss
Added documentation outlining how to stack SDS icons.
Added one css tweak to address space added to bottom of SVG due to display:inline-block being applied to element. Without this there is ~0.1 em added to the bottom which messes with alignment.
https://cm-jira.usa.gov/browse/IAEDEV-45484
=> Add documentation section for stacking icons

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
With the new history changes, the layout component is now responsible for route navigation. The issue here is that the navigation done seems to update the query params just fine, but resets the url to base path rather than whatever path it currently is on.
See Stackblitz Example - https://stackblitz.com/edit/angular-gcf63x-5qwnl1?file=src%2Fapp%2Fsidenavigation-optional.module.ts
Navigate through domain selection, and the path changes to `/testPath`, however typing some word in the filter portion afterwards removes the `testPath` from the url when it should only do query parameter updates.
=> Update route navigation url in result list

libs/packages/components/src/lib/side-navigation/model/side-navigation-model.ts, libs/packages/components/src/lib/side-navigation/side-navigation.component.html, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Stems from https://cm-jira.usa.gov/browse/IAEDEV-46387 - Users are currently using updateFilter method in resultList to manually update their filter model. However, they are also forced to perform route navigation when they do. This change adds an optional parameter to updateFilter method to disable route navigation when updating filters.
https://cm-jira.usa.gov/browse/IAEDEV-46387
#500
=> Add optional parameter to merge queryparam in sidenav

libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.ts
The accordions in our demo were not expanding/closing when the buttons 'Open First Item' / 'Close First Item' was clicked. Seems to be due to the OnPush change detection strategy preventing change detection when the expanded value changed
https://cm-jira.usa.gov/browse/IAEDEV-46469
=> Remove onpush change detection strategy

libs/packages/sam-material-extensions/tsconfig.lib.prod.json
Add missing tsconfig.lib.prod.json file for sam-material-extensions library
=> Add prod build options for material extensions

libs/documentation/src/lib/components/table/demos/full/full.component.html, libs/documentation/src/lib/components/table/demos/pagination/pagination.component.html, libs/packages/sam-formly/src/lib/formly/types/datepicker.ts, libs/packages/sam-formly/src/lib/formly/types/daterangepicker.ts
Resolves issue with pagination demo where the list was not paginated. Updates styling of datepicker so that the calendar button does not wrap into a separate line
=> update pagination demo and add flex display for datepicker with toggle

libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
Update logic of autocomplete to accept consecutive updates - Considering our current logic, if something were to write the same value to autocomplete component twice, the first time it would update normally, but the second time, it would go into the else condition (line 98-99 in autocomplete.ts), and potentially reset the autocomplete model in line 102.
=> Update write valuelogic of autocomplete to accept duplicate updates

libs/documentation/src/lib/components/popup/demos/basic/popup-basic.component.html, libs/packages/sam-formly/src/lib/formly/types/fileinfo.ts
Updates popup demo so that the div's that contain the pop-up directive can be focused on and display the tooltips through keyboard.
Updates fileinfo so that each fileinfo item can be focused and properly selected through enter key press
=> Update focus issues on popup and fileinfo

libs/documentation/src/lib/pages/layout/layout.component.ts, libs/packages/layouts/src/lib/feature/search-list-layout/model/search-list-layout.model.ts, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Add option for users to define what default filter values should be if there are no filter values in URL
=> Add default value option for layout component

libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
Adds CSS styling that overrides USWDS' style for table. This change will remove table/cell borders in the angular material calendar for all our date-pickers
=> Remove borders in table for material calendar in datepickers

libs/packages/sam-formly/src/lib/formly/types/datepicker.ts, libs/packages/sam-formly/src/lib/formly/types/daterangepicker.ts, libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
Resolves issue where accordion wrappers around datepicker would auto-close when the datepicker runs into validation errors.
Resolves issue of datepicker's templateoption's onchange not being called when a date is selected from calendar
#536
=> Resolve datepicker accordion autoclose and onChange not firing

libs/documentation/src/lib/components/collapse/demos/basic/collapse-basic.component.html, libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html, libs/packages/components/src/lib/selection-panel/selection-panel.component.html
Resolves 2 issues seen in autocomplete and in selection panel components - 
In autocomplete, JAWS was announcing the drop down options icon in autocompletes as 'Clear Input'
In selection panel, JAWS was not properly announcing the aria-label of list header
=> Resolve jaws issues in autocomplete and selection panel

libs/packages/layouts/src/lib/feature/subheader/subheader.component.scss
Flex style was causing buttongroup to collapse down on IE, when removing it the issue resolves itself. Flex is only needed for mobile view, so updated styling so that flex is only applied for mobile.
https://cm-jira.usa.gov/browse/IAEDEV-46051
=> IAE-46051: Remove style causing issue

libs/packages/components/src/lib/video-player/css/px-video.css
#544 - Sprites did appear when running locally, but failing in federalist build mainly because federalist contains non-empty string for base href. We were picking up some of the sprites from applications' assets directory rather than using a local one. Switched to using local svg file rather than the one in application's assets directory as we cannot always assume the application will have the image we need or know the path to it.
=> Resolving pathing issue for video player controls

libs/packages/components/src/lib/side-navigation/side-navigation.component.html
Reported by brandy from entity team - when navigating from sidenav to a link with no query parameters, the navigation would not remove pre-existing query params
=> remove default queryparams handling

libs/packages/components/src/lib/pagination/pagination.component.html, libs/packages/components/src/lib/search-result-list/search-result-list.component.html
After performing a search, JAWS does not announce to the user whether the search results have changed or not. The changes here adds aria live region on pagination elements such that if the number of search results change, JAWS will announce the updated number of search results. Additionally, aria live region is added around the no results found template so that JAWS will announce that there are no results in the case where there are none.
JIRA - https://cm-jira.usa.gov/browse/IAEDEV-46493
=> Add aria live regions for new search results

libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
From JIRA ticket - https://cm-jira.usa.gov/browse/IAEDEV-46485
Updated to use labelText for aria labels if an aria label is not provided for autocomplete components
=> Use provided labelText as default for autocomplete

libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
Formly configs with hideexpression in them were not being kept on reload with history enabled. Formly does not create form controls for fields that are hidden, so when history attempts to update the filterModel using `form.patchValue` the hidden field configs are not properly set because those form controls do not get created
#540
=> Update sds-filters to adjust for hideexpression configs

libs/packages/sam-formly/src/lib/formly/types/radio.ts
When a user places two radio configs inside a formly field group, it is currently being treated as one radio group:
The above configuration creates an issue where JAWS will announce the sum total of all radio options - in the example above, JAWS will indicate that there are 4 options when really there are two options for each of the two radio group. Additionally, pressing tab will completely skip over the second radio group because the markup believes that there is only 1 radio group.
https://cm-jira.usa.gov/browse/IAEDEV-46495
Solution taken from SO: https://stackoverflow.com/questions/28543752/multiple-radio-button-groups-in-one-form
=> Resolve issue with different radio groups in same field group being treated as one

apps/sam-design-system-site/src/material.theme.scss, libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.html, libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
Jira issue - https://cm-jira.usa.gov/browse/IAEDEV-46964
Github Issue #528 
Angular material sets CSS outline property of accordion headers when in focus to 0, overriding USWDS's default outline on focus. This changes overrides that override and resets it back.
=> Update accordion styling

libs/documentation/src/lib/components/shared/examples-page/demo.component.ts
With the recent changes, I've noticed that when setting up new demos, the requirements to get it working with stackblitz was quite obscure and often tricky to get it working - with the requirements of some directory names needing to match demo names. This was because when the stackblitz demo files are generated, the script uses directory names in deciding where to place those files, while when retrieving them, runtime application logic uses the given name of the demo. This PR updates such that when retrieving the demo files during runtime, it also looks at directory names - which should make it a bit easier for new demos to be auto-integrated with stackblitz.
=> Update logic in retreiving generated stackblitz files

libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts, libs/packages/sam-formly/src/lib/formly/types/radio.ts
Current logic in autocomplete is to use the araiLabel for aria-label attribute if provided, otherwise use label text. However, since ariaLabel is assigned a default value of 'Auto Complete', the labelText property is never applied when ariaLabel is not provided by users.
=> Remove default aria-label on autocomplete model

libs/documentation/src/lib/components/selection-panel/demos/basic/basic-selection-panel.component.html, libs/documentation/src/lib/components/selection-panel/demos/default-selection/default-selection-panel.component.html, libs/documentation/src/lib/components/selection-panel/demos/default-selection/default-selection-panel.component.ts, libs/documentation/src/lib/components/selection-panel/demos/default-selection/default-selection-panel.module.ts, libs/documentation/src/lib/components/selection-panel/demos/default-selection/navigation.config.ts, libs/documentation/src/lib/components/selection-panel/selection-panel.module.ts, libs/packages/components/src/lib/selection-panel/selection-panel.component.html, libs/packages/components/src/lib/selection-panel/selection-panel.component.ts
Update selection panel component to allow default selection of sub panels in children array in addition to main panels and add an example for demo. Update ngOnChanges logic to allow users to programmatically update selected panel. Refactor HTML to distinguish between main panel and sub panel css.
=> Update Selection Panel Component

libs/packages/sam-formly/src/lib/formly/wrappers/form-field.accordian.ts
This issue of accordion auto-closing for date was previously fixed, but for group wrappers only. This adds the fix to accordion wrappers as well
#536
=> Apply fix for accordions auto-closing on date validation error

libs/documentation/src/lib/pages/layout/data.service.ts, libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html, libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts, libs/packages/layouts/src/lib/feature/search-list-layout/model/search-list-layout.model.ts, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts, libs/packages/sam-formly/src/lib/formly-filters/service/sds-filters-comunication.service.spec.ts, libs/packages/sam-formly/src/lib/formly-filters/service/sds-filters-comunication.service.ts
This change adds additional input to search-list-layout that allows users to disable the api call. This is necessary for responsive layout view because any changes to filters should not make get data call when the responsive dialog for toolbar is open - that should only happen after the 'Apply' button has been clicked and the dialog is closed. Additionally, update the responsive layout demo to use the new option and perform search after 'Apply' is clicked
https://cm-jira.usa.gov/browse/IAEDEV-47539
=> Add option to disable api call in layout component and update responsive layout demo

libs/packages/components/src/lib/video-player/css/px-video.css, libs/packages/components/src/lib/video-player/video-player.component.ts, libs/packages/sam-formly/src/lib/formly/formly.module.ts, libs/packages/sam-formly/src/lib/formly/types/radio.spec.ts, libs/packages/sam-formly/src/lib/formly/types/radio.ts
Fixes issue for radio buttons being grouped in one form. Resolves accessibility issue where AMP was flagging the progress bar in video as not having an accessible name value. Updates styling so that the timer on hover of progress bar renders properly and the cursor is the correct type.
git #574
=> Git 574 radio issue and 508 video fix

libs/packages/components/src/lib/external-link/external-link.directive.spec.ts, libs/packages/components/src/lib/external-link/external-link.directive.ts
Amp flags external links that don't warn the users when a link will open new window, so this change updates the external link directive to add an aria label to notify the users. The label is only added if an aria label does not already exist in the link.
=> Add aria label for external links

libs/packages/components/src/lib/pagination/pagination.component.html, libs/packages/layouts/src/lib/feature/actions-menu/actions-menu.component.html
Updates pagination component's input so that it also announces total pages to the user on focus.
Updates menu component's sr only message to not include the word 'Menu' as it is added by screen readers for buttons with role="menu"
git #585 
git #588
=> Update pagination input to include total pages

libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html, libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts
Small update to demo for responsive layout component - separate the variable used for card expand/collapse for domain and filters  so that they can be controlled separately
=> update card expand/collapse toggle for responsive layout

libs/documentation/src/lib/components/filters/demos/defaultValues/filters-default-value.component.html, libs/documentation/src/lib/components/filters/demos/defaultValues/filters-default-value.component.ts, libs/documentation/src/lib/components/filters/demos/defaultValues/filters-default-value.module.ts, libs/documentation/src/lib/components/filters/filters.module.ts, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.spec.ts, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts, libs/packages/sam-formly/src/lib/formly-reset/formly-reset.component.ts
With responsive layout introduced, sds filters is initialized anytime advanced search is clicked, and destroyed anytime the responsive modal closes. During init, formly uses current model values to define what the initial values are to reset the form back to when users do resetModel. The issue with resetAll occurs because opening the responsive model, entering some values, applying those values, then re-opening the model changes what the default values for sds filters' formly are because the form gets re-initialized, but with default values of whatever the current model is. This change adds an input to sds filters for developers to pass in the default values to reset to and allows for a separation of what the model is during formly initialization vs what the values should be on form …
=> Update sds filters to allow users to pass in default model

libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
Issue discovered by atomic tangerine and recorded in this git ticket - #609 
This issue was caused as a result of fix for this git issue - #540 - The change there had re-assigned the model to updatedModel to account for hideExpression filters. The issue this caused is that because the reference to model changed, formly rebuilt it's form from it's ngOnChanges - https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/components/formly.form.ts#L81 - which caused the perceived default value to update, and break resetAll functionality.
This update keeps the copy of the updatedModel to sds filters' model, but does so without changing reference. This way, ngOnChanges is not triggered, and formly does not re-build its form
=> Perform shallow copy of model on filter change rather than changing model reference

libs/packages/sam-formly/src/lib/formly/types/radio.ts, libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts
When initially tabbing on to a radio group, the label and descriptions were not previously being read by screen readers. Updates to add aria label and aria describedby to radio group's form element
https://cm-jira.usa.gov/browse/IAEDEV-46491#
=> Add described by aria label to radio group form

libs/documentation/src/lib/components/system-alerts/demos/multiple/system-alerts-multiple.component.html, libs/documentation/src/lib/components/system-alerts/demos/multiple/system-alerts-multiple.component.ts, libs/documentation/src/lib/components/system-alerts/demos/single/system-alerts-single.component.html, libs/documentation/src/lib/components/system-alerts/demos/single/system-alerts-single.component.ts, libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.ts
Adds output event when an alert is dismissed so that applications are able to keep track of dismissed alerts and not re-render on page refresh
=> Add output event when an alert is dismissed

libs/packages/components/src/lib/autocomplete-search/models/SDSAutocompleteConfiguration.ts
The ariaLabel default was previously removed for autocompleteconfiguration model and merged in - https://github.com/GSA/sam-design-system/commit/f9da43f72cc29718ca05f22cf28bdfb10069159b#diff-6f0ecbedcda2523749a35b93eb7df9740cc94e5cde919b4a63360d62f3a2933d
However, we have another similar model `SDSAutocompleteSearchConfiguration` for which the ariaLabelText default string was not removed
=> Remove aria-label default from autocomplete-search-configuration

libs/documentation/src/lib/components/formly-input/demos/optional/input-optional.component.ts, libs/packages/sam-formly/src/lib/formly/types/input.ts, libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts, libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
=> Disable css changes for Input and label

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts, libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts, libs/packages/sam-formly/src/lib/formly-filters/service/sds-filter-model-update.service.ts, libs/packages/sam-formly/src/lib/formly-filters/service/sds-filters-comunication.service.ts
Contains small bugfixes to toolbar, layout, and sds-filters for bugs discovered while integrating the responsive sidenav. 
sds-side-toolbar no longer emits a responsiveDialog event on screen size change if the dialog is already closed.
layout component uses href property to evaluate query params in order to account for hashes in url
sds-filters updatefiltermodel is changed to a behavior subject while communication service's subject is reverted back from BehaviorSubject to regular Subject
=> Multiple fixes for responsive sidenav during prototype integration

libs/packages/components/src/lib/search/search.component.html, libs/packages/sam-formly/src/lib/formly/types/radio.ts, libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
Resolves various github issues:
#622 - Adjusts height for accordion header to allow larger texts in accordion heading
#621 - Removes role of radio group from radio form element as it was being flagged by access assistant
#619 - Removes sr-only label for search button and instead uses aria label for screen readers
=> fixes for github issues 622, 621, and 619

libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts
Resolves a typo on logic for side toolbar's breakpoint observer.
=> Fix typo on side toolbar logic change

libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
There was slightly more space added for min-height than needed on a previous change where the text on accordion header was cutting off - https://github.com/GSA/sam-design-system/issues/622
This change re-adjusts the height of accordion header back down to 34 px
https://github.com/GSA/sam-design-system/issues/622
=> Update min height of accordion

libs/packages/sam-formly/src/lib/formly/types/radio.ts
#621 - Amp likely flagging cases where aria-describedby points to a description id, but no description was provided, so element with the describedby id does not exist. Updates to conditionally add aria-describedby to radio form group only if a description exists.
#621
=> git 621 - aria-describedby added to radio form only if description is given

libs/documentation/src/lib/components/formly-datepicker/demos/daterange/datepicker-daterange.component.ts, libs/packages/sam-formly/src/lib/formly/formly.config.ts
Setting hideoptional to true should hide optional in label for daterangepicker
#642
=> Hideoptional should not display optional label for daterange picker

libs/packages/sam-formly/src/lib/formly/formly.config.ts
Moves hideoptional expression for date range picker to exported function to allow prod build.
=> Move hideoptional method into exported function for date range picker

libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
From github issue #632 - Accordion items are not properly aligned in IE
=> Resolve height issue for accordion in ie

libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html, libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts, libs/packages/components/src/lib/public-api.ts, libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts
From github issue #650 - Updated to allow users to pass in dialog options for responsive toolbar.
Allowing users to pass in dialog options would let them define certain properties of the responsive dialog modal - including aria label
=> Add dialog config option for side toolbar

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts, libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts, libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
Updates css for accordion to have border radius for 1st and last item, but adds exception for accordions inside a card list
Layout component, on destroy, will fire an update filter event resetting the filter value to null
Responsive sidenav modal will auto close if the user resizes their window to be greater than 480 px
=> Update accordion css, reset filter on layout destroy, auto close responsive modal on window resize

libs/packages/components/src/lib/selected-result/selected-result.component.html
A couple aligment issues were reported after updating to the latest SDS version. This PR addresses one of them, the other is fixed in sam-styles
A couple aligment issues were reported after updating to the latest SDS version. This PR addresses one of them, the other is fixed in sam-styles
Before
After
=> Fixing selected result alignment issue

libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.html, libs/packages/components/src/lib/external-link/external-link.directive.ts
This was requested by Christy during sync up meeting with Cotton Candy and Atomic Tangerine. Until fsd.gov supports links to navigate the user back to beta.sam, it will be considered an external link.
=> Remove fsd from internal links exception

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.spec.ts, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
We reset page number to 1 anytime filter update occurs - when clicking browser back button, we don't know for sure what values would be different, so we assume a filter change also occurs, and therefore, were resetting page number to 1 on back button click. Updated to let layout know not to reset page whenever we retrieve history from url
=> Set page default to true when retreiving history from url

libs/packages/components/src/lib/video-player/video-player.component.html, libs/packages/components/src/lib/video-player/video-player.component.ts
This issue was mainly noticed in IE and Edge. Video elements have a preload attribute that hint to the browser when they'd want to fetch data for the video. We generally prefer to wait until the user has interacted with the video (pressed play) and then fetch the data rather than eagerly fetch and waste potential network data. The issue is that browsers can choose to ignore this attribute and eagerly fetch anyways even when suggested not to. Therefore, we do not include the video source in the DOM until the user demands for it, causing browsers that do pre-fetch to also wait until a source is available in the DOM.
=> Delay loading of video source when preload is none

libs/documentation/src/lib/pages/layout/layout.component.html, libs/documentation/src/lib/pages/layout/layout.component.ts, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts, libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html, libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
Javascript treats 'true' / 'false' strings as literal strings and therefore are truthy. The change here updates the comparison logic in layout to treat 'true' / 'false' values as boolean rather than strings such that something with value of 'true' will the boolean value of true. Likewise with false string.
#656 - This only resolves the comparision with default model as mentioned in the comment of that issue and DOES not resolve the original posted issue.
=> Update default model comparison to treat 'true' / 'false' string as boolean values

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Updates logic in layout to display loading regardless of results are initially available or not. Also moves the loading state outside set timeout in order to avoid any flickers in UI between different displays (No Matches vs loading)
=> Search layout display loading on search

libs/packages/components/src/lib/video-player/video-player.component.html, libs/packages/components/src/lib/video-player/video-player.component.ts
On mobile, in chrome, video players do not render the controls the same way, so the progress bar html query was returning null and throwing an error in the following aria label attribute addition. Which then prevented the remaining code to add video source from executing. Update to add check so that progress bar is only modified if the query is able to find it in the html
=> Video player mobile issue

libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.html, libs/packages/components/src/lib/side-navigation/side-navigation.component.html, libs/packages/components/src/lib/side-navigation/side-navigation.component.ts
Add aria label input option for sds side navigation component.
#675
=> Add aria label input for sidenavigation component

misc/stackblitzes-templates/app.module.ejs
Some of the recent changes had caused the stackblitz app module file to contain syntax errors - applies fix for changes to app module for stackblitz script
=> Update app module for stackblitz template

libs/documentation/src/lib/pages/layout/layout.component.html, libs/documentation/src/lib/pages/layout/layout.component.ts, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
Empty filter values should also be considered as default and display instructions to users to Select Criteria
Changes to checkbox / multi-checkbox should consistently use boolean values when checked / unchecked - currently the conversion to clean model was changing them to strings
#704
=> Treat empty filters as default, consistently use boolean for checkboxes

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
This change removes a previous change where select criteria would show if filter model was empty even if that empty model was not equal to default model. Upon discussion in Friday's grooming, it was decided that if the user clears out the filter model, then we should display all data rather than showing select criteria so long as the empty model was not equal to default model
Revert a previous change in this commit - https://github.com/GSA/sam-design-system/commit/f9f4f5b5f68171cf3bf340e800313b373a268f7a
=> Results should display whenever filter is not default - no exception

libs/packages/components/src/lib/selection-panel/sub-panel/sub-panel.component.html
Resolves issues related to very low contrast for selection panel component. Added classes are defined in sam styles in this PR: https://github.com/GSA/sam-styles/pull/452
#683 #689
=> Resolve contrast issues on subpanel component

libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.html, libs/packages/components/src/lib/external-link/external-link.directive.spec.ts, libs/packages/components/src/lib/external-link/external-link.directive.ts
Changes to external link directives:
If an aria label is provided for the external link, but label does not contain key words 'new' and 'window', the text '- opens in a new window' will be appended to the aria label
If no aria label is given, then the directive will first attempt to use the innerText. If the anchor tag contains any children nodes (icons, span tags, etc), then the href value will be used instead
If an aria label is provided and the label does indicate the link will open in a new window, then the label will remain as is
#688
=> Git 688 external link directive update

libs/documentation/src/lib/components/formly-radio/demos/advanced/radio-advanced.component.html, libs/documentation/src/lib/components/formly-radio/demos/advanced/radio-advanced.component.ts, libs/documentation/src/lib/components/formly-radio/demos/advanced/radio-advanced.module.ts, libs/documentation/src/lib/components/formly-radio/radio.module.ts, libs/packages/sam-formly/src/lib/formly/types/radio.html, libs/packages/sam-formly/src/lib/formly/types/radio.ts
Update radio formly to allow description array property for each option, where each description will be rendered in a new line underneath the radio's main label. 
IAE-51928
=> Allow multi-line strings for radio options

apps/sam-design-system-site/src/app/app.component.html, libs/documentation/src/lib/components/date-pipe/date-pipe.module.ts, libs/documentation/src/lib/components/date-pipe/demos/basic/date-pipe-basic/date-pipe-basic.component.html, libs/documentation/src/lib/components/date-pipe/demos/basic/date-pipe-basic/date-pipe-basic.component.ts, libs/documentation/src/lib/components/date-pipe/demos/basic/date-pipe-basic/date-pipe-basic.module.ts, libs/documentation/src/lib/documentation.module.ts, libs/packages/components/src/lib/date/sds-date.module.ts, libs/packages/components/src/lib/date/sds-date.pipe.spec.ts, libs/packages/components/src/lib/date/sds-date.pipe.ts, libs/packages/components/src/lib/public-api.ts
Added date pipe to implement custom date logic. If passed in date is today, the time will be displayed. If in this year, only month and day will show. If a different year; month, day, and year will show.
https://cm-jira.usa.gov/browse/IAEDEV-49954
=> IAEDEV-49954: Add date-pipe

libs/packages/components/src/lib/date/sds-date.pipe.spec.ts
Fixes tests which expected that minutes wouldn't be zero padded when less than 10. This fix pads expected value with '0' if less that 10 to match shortTime
Tests fail when minute value less than 10, this PR fixes those tests
=> Fix tests with wrong expectation

libs/documentation/src/lib/components/search/demos/optional/search-optional.component.ts, libs/packages/components/src/lib/search/search.component.html, libs/packages/components/src/lib/search/search.component.scss
Fixes issue where when dropdown is shown, it takes up 50% of the area whereas it used to take up less. This caused issues where placeholder text was not fitting in textarea. Also fixes an issue in IE where suffix icon was not aligned.
https://cm-jira.usa.gov/browse/IAEDEV-51540
=> IAEDEV-51540: Fix search widths

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
For retrieving query string from browser, look at location.search rather than href, as search only extracts the query values
On navigation, if url contains any fragments, keep those values
#700
=> Account for url fragments

libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.html, libs/packages/components/src/lib/date/sds-date.pipe.spec.ts, libs/packages/components/src/lib/external-link/external-link.directive.spec.ts, libs/packages/components/src/lib/external-link/external-link.directive.ts
Anchor tags with href that start with the word 'mailto' will not be modified by the external link directive
#728
=> Treat mailto links as internal links

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
These changes prevent scrolling when applying filters, add pageSize to the querystring and fix and issue where user is not able to navigate back to previous page after applying a filter
https://cm-jira.usa.gov/browse/IAEDEV-52855
https://cm-jira.usa.gov/browse/IAEDEV-53168
https://cm-jira.usa.gov/browse/IAEDEV-52675
=> IAE-52885: Update logic to prevent scrolling when user applies filter

libs/documentation/src/lib/components/formly-readonly/demos/basic/readonly-basic.component.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-container.component.html, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-autocomplete.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-checkbox.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-datepicker.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-daterange.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-fileinfo.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-input.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-multicheckbox.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-radio.ts, libs/packages/sam-formly/src/lib/formly/readonly/readonly-types/readonly-select.ts
Expand readonly components to accept template options to allow tags in labels
=> Display label tags in readonly mode

libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.ts, libs/packages/components/src/lib/search-result-list/model/search-results.model.ts, libs/packages/components/src/lib/search-result-list/search-result-list.component.html
Adds ariaLabel option for button list in results-list model
=> Allow arial label options for no matches template button

libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
git #733 - Check for hide not properly hiding sibling fields
=> Fix issue where hidden siblings are also displayed during checkForHide

libs/packages/components/src/lib/search/search.component.ts
fix SearchSettings fields to be correctly marked as optional to allow for accurate type checking
make SearchSettings type safe
we have turned on typechecking and having all fields required breaks our code and is unnecessary when using default values
- [x ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [x ] Chrome
=> make optional params for SearchSettings optional

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Resolve issue described in #754
Perform navigation by skipping history when adding default page number or size
=> Resolve recursive navigation due to page params

libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.html, libs/packages/components/src/lib/search-result-list/search-result-list.component.html, libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
Update blocks for loading in demo based on feedback - 
Content blocks will be slightly smaller
Slight spacing between loading blocks
=> Update loading blocks based on demo feedback

libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.html, libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
Updates size of down caret in horizontal filter popover to be slightly smaller
=> Demo feedback update - caret down should be smaller

libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts, libs/packages/sam-formly/src/lib/formly-reset/formly-reset.component.ts
Add output events for applications to listen and react to:
layout's sort by filter value changes
Sds-filter's reset button click event
=> Add output event on sortfield change and on reset click

libs/documentation/src/lib/components/filters/demos/horizontal-filter/horizontal-filter.component.html, libs/documentation/src/lib/components/filters/demos/horizontal-filter/horizontal-filter.component.ts, libs/documentation/src/lib/components/filters/demos/horizontal-layout/horizontal-layout.component.html, libs/documentation/src/lib/components/filters/demos/horizontal-layout/horizontal-layout.component.ts, libs/documentation/src/lib/components/filters/demos/horizontal-layout/horizontal-layout.module.ts, libs/documentation/src/lib/components/filters/filters.module.ts, libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.scss, libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts, libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts, libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
Small demo for how fields can be displayed horizontally in sds filters through grid css classes
Updates autocomplete to hide cursor in both multi or single select view during input readonly mode
Updates label to allow labelClass template option for defining additional css to labels
=> Add demo for horizontal layout

package-lock.json, package.json
Increment the version of ngx-uswds-icons used by sam design system, this version was created to address issue raised by https://github.com/GSA/sam-styles/issues/469 by adding a class, icon-display-block, to usa-icon which sets display:block on the icon's svg. 
Needed to address issue raised by https://github.com/GSA/sam-styles/issues/469 by adding a class, icon-display-block, to usa-icon which sets display:block on the icon's svg.
=> IAE-56716: Update ngx-uswds-icons version to 0.0.7

libs/documentation/src/lib/pages/layout/filter.service.ts, libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts, libs/documentation/src/lib/pages/layout/layout.component.ts, libs/packages/components/src/lib/autocomplete/autocomplete.component.ts, libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts, libs/packages/components/src/lib/selected-result/models/SDSSelectedResultConfiguration.ts, libs/packages/components/src/lib/selected-result/selected-result.component.html, libs/packages/components/src/lib/selected-result/selected-result.component.ts
Add a function input option for autocomplete configuration that allows users to modify autocomplete chip display value
Add additional observable users can trigger for when they want to force autocomplete to run change detection
This will allow users to add prefix / suffix as needed to their chips
=> Add display modifier function for autocomplete chips

misc/generate-stackblitzes.ts
As of this PR posting, stackblitz does not recognize 10.0.4 has been released. It's slow to pick up new version release, so locking demo at 11.0.3 temporarily
=> Lock stackblitz demo at 11.0.3

misc/generate-stackblitzes.ts
Update styling reference to sds.css rather than styles.css
=> Resolve styling issue for stackblitz

apps/sam-design-system-site/src/app/app.component.html, libs/documentation/src/lib/components/actions/demos/basic/actions-basic.module.ts, libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.module.ts, libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.module.ts, libs/documentation/src/lib/components/result-list/demos/card/result-list-card-component.module.ts, libs/documentation/src/lib/components/result-list/demos/component/result-list-component.module.ts, libs/documentation/src/lib/components/result-list/demos/template/result-list-template.module.ts, libs/documentation/src/lib/pages/layout/layout.module.ts, libs/packages/components/src/lib/actions-menu/actions-menu.component.html, libs/packages/components/src/lib/actions-menu/actions-menu.component.ts, libs/packages/components/src/lib/actions-menu/actions-menu.module.ts, libs/packages/components/src/lib/public-api.ts, libs/packages/components/src/lib/side-toolbar/side-toolbar.component.html, libs/packages/components/src/lib/side-toolbar/side-toolbar.component.spec.ts, libs/packages/components/src/lib/side-toolbar/side-toolbar.component.ts, libs/packages/components/src/lib/side-toolbar/side-toolbar.module.ts, libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts, libs/packages/layouts/src/lib/feature/subheader/subheader.module.ts
Moves the action menu and side-toolbar components out of layout package to component package. These two components currently do still exist in layouts in order to give time for users to switch dependency to use @gsa-sam/components rather than layouts. There is a deprecated warning message thrown to console however informing devs to switch their dependency.
separating layouts from the other gsa packages
=> Move action menu and responsive side nav to components package

.circleci/config.yml
Updates the circle-ci script to run the publish:libs script in dry run so that all packages also get a prod build
=> Update circle ci to also run prod build

libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html, libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.scss, libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
Adjust autocomplete overlay's min width to be same as input field's min width. Remove fixed restriction of min-width: 30rem for autocomplete results.
Resolves issue where if the input width is less than 30rem, the result list would still be 30 rem rather than the same width as the autocomplete input field
=> Fix autocomplete width issue

libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts, libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.ts
Resolves issue where attempting to display hidden filters from More Filters would throw undefined error
=> Resolve undefined issue with more filters dialog

libs/documentation/src/lib/components/selection-panel/demos/default-selection/default-selection-panel.component.html, libs/documentation/src/lib/components/selection-panel/demos/default-selection/default-selection-panel.component.ts, libs/packages/components/src/lib/selection-panel/navigation-mode/navigation-mode.component.html, libs/packages/components/src/lib/selection-panel/navigation-mode/navigation-mode.component.ts
Resolves issue where clicking on child link on selection panel would not visually indicate the item was selected
=> Update selection panel to recursively select children

libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.html, libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.ts, libs/packages/sam-formly/src/lib/formly-stepper/sds-step-buttons.ts, libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
Updates to stepper component:
Updates behavior of the next button to always be enabled in linear mode. Clicking next on an invalid step with defined 
inputs will trigger validation for that step and display validation errors
Updates toggling of linear mode to be more dynamic. Watch for change to linear input and update step configs 
automatically
=> Stepper updates

libs/documentation/src/lib/pages/layout/filter.service.ts, libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts, libs/packages/sam-formly/src/lib/formly/wrappers/form-field.accordian.ts, libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
Added logic to perform an additional hide check whenever layouts fires filter change
Update the way group wrapper opens and closes accordion. On initialization, accordions with defined models are opened. Then we listen for resetAll event and close accordions with empty model when the reset button is clicked. Sds Filters is given responsibility of emitting the resetAll event when reset all is clicked
=> Resolve usa-accordion issues with sds-filters

libs/documentation/src/lib/components/formly-multicheckbox/demos/basic/multicheckbox-basic.component.ts, libs/packages/sam-formly/src/lib/formly/types/checkbox.ts, libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html, libs/packages/sam-formly/src/lib/formly/types/radio.html
Update how we add labels to templates for checkboxes and radios. Use innerHTML rather than string interpolation binding to allow custom template for labels - such as anchor tags
#868
=> Treat label inputs as base html for checkbox and radios

libs/documentation/src/lib/components/tree-table/demos/basic/tree-table-basic.component.html, libs/documentation/src/lib/components/tree-table/demos/basic/tree-table-basic.component.ts, libs/packages/components/src/lib/tree-table/tree-table.component.html, libs/packages/components/src/lib/tree-table/tree-table.component.ts
Update truncation options for children in tree - Adds an option for max limit on number of children to display and another input config that defines how many children to display if we're over that max.
=> Update tree table to allow max children limit

libs/packages/components/src/lib/tree-table/tree-table.component.html, libs/packages/components/src/lib/tree-table/tree-table.component.ts
Update expansion behavior for tree table such that if totalChildren of a row is greater than 0, we show the expansion indicator. Previously, we were only considering the length of row's children before showing expansion indicator, however, in the event that users want to lazy load children entirely until expansion is clicked, this children would be null while totalChildren value would be non-zero.
=> Update expansion behavior for tree table

libs/packages/components/src/lib/tree-table/tree-table.component.ts
Once a table row is collapsed, the `viewAllChildren` state resets to false. This state is used to define whether user has clicked on 'View All' for a tree table row. This change effectively allows a way for users to hide children that were displayed by clicking on 'View All' button
=> Reset View All for tree table rows on collapse

libs/packages/components/src/lib/tree-table/tree-table.component.ts
Resolve UI isue with tree table vertical border where rendering table rows of greater height caused vertical border to be out of alignment with the horizontal ones.
Initially brought to attention after a tree table demo done last sprint in design system parking lot
=> Adjust bottom value of vertical border in tree table based on row height

libs/documentation/src/lib/components/filters/demos/horizontal-filter/horizontal-filter.component.ts, libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
Update demo of horizontal filters to use date range with hide expression behavior
Update popover wrapper to allow template options to toggle close behavior (Auto close on external click vs closing only on the button that toggles popup)
=> Horizontal filters datepickers

libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
Potential fix for #860 - Nested filters with values not being displayed to the user on init.
=> Display nested filters with values if hidden

apps/sam-design-system-site/src/app/app.component.html, libs/documentation/src/lib/components/expires/demos/basic/expires-basic.component.html, libs/documentation/src/lib/components/expires/demos/basic/expires-basic.component.ts, libs/documentation/src/lib/components/expires/demos/basic/expires-basic.module.ts, libs/documentation/src/lib/components/expires/expires.module.ts, libs/documentation/src/lib/documentation.module.ts, libs/packages/components/src/lib/expires/expires.directive.ts, libs/packages/components/src/lib/expires/expires.module.ts, libs/packages/components/src/lib/public-api.ts
Adds expires structural directive to SDS components This directive is used to set an 'Expiration Date' for a html element. If user's current time  is past the expiration date, then the element will be hidden from the user.
=> Add directive to allow expiration dates on elements

libs/documentation/src/lib/components/formly-radio/demos/template/radio-template.component.html, libs/documentation/src/lib/components/formly-radio/demos/template/radio-template.component.scss, libs/documentation/src/lib/components/formly-radio/demos/template/radio-template.component.ts, libs/documentation/src/lib/components/formly-radio/demos/template/radio-template.module.ts, libs/documentation/src/lib/components/formly-radio/radio.module.ts, libs/packages/sam-formly/src/lib/formly/types/radio.html, libs/packages/sam-formly/src/lib/formly/types/radio.ts
Updated formly radio template to allow developer to specify template that is rendered for each radio option.
Added demo showing how a developer might add a template in ngAfterInit method
https://cm-jira.usa.gov/browse/IAEDEV-65328
=> IAE-65328: Add option to pass radio option template

libs/packages/components/src/lib/search/search.component.html
Search icon was no longer showing on button in search component. This PR added a usa-icon to that button. Styling for this PR is in [sam-styles](https://github.com/GSA/sam-styles/pull/537)
Search icon was no longer showing on button in search component.
Before:
After:
=> Add icon to search button

libs/documentation/src/lib/components/formly-stepper/demos/advanced/custom-stepper.component.html, libs/documentation/src/lib/components/formly-stepper/demos/uswds-stepper/uswds-custom-stepper.component.html
Updated classes applied to buttons in stepper examples. Specifically removed `padding-2`. This class made no change to the appearance on other browsers, but in safari it pushed the icons down.
#938
=> Remove padding-2 class to center icons in safari

angular.json, apps/sam-design-system-site/src/sds-styles.scss, misc/generate-stackblitzes.ts
For some reason sam-styles was commented out and only uswds was being applied. Updated sds-styles.scss to apply sam-styles and remove uswds, except what is not overridden in sam-styles. Also fixed angular.json
With changes applied:
=> Fix appearance of SDS site

libs/packages/components/src/lib/dialog/dialog-container.component.html, libs/packages/components/src/lib/dialog/dialog.module.ts
Updated dialog container to use exclamation-circle rather than alert-error icon when alert type is error.
https://cm-jira.usa.gov/browse/IAEMOD-1254
=> IAEMOD-1254: Change error icon in alert modal

libs/documentation/src/lib/components/video/demos/basic/video-player-sample-data.ts, libs/packages/components/src/lib/video-player/video-player.component.ts
Update video selectors to expect id as part of selector
#996
=> IAEMOD-1526: Update video selectors to expect id as part of selector

libs/packages/components/src/lib/video-player/video-player.component.ts
Video player was throwing an error when  id provided in config contained a period. This PR updates the logic to get the video element to use childRef rather than css selector.
https://cm-jira.usa.gov/browse/IAEMOD-2786
=> IAEMOD-2786: Update code to use childRef rather than css selector

libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts, libs/packages/sam-formly/src/lib/formly/wrappers/tabs.wrapper.ts
Addresses #1035
Tested and confirmed this behavior was only occurring within tabs-formly wrapper. Wrapper was not setup to allow updated model to be passed to components in panel, this PR updated model being passed to components with each value update. Filter logic also needed to be updated slightly so that when filterUpdateModelService was updated, the form would be updated immediately, rather than having a slight delay added by setTimeout.
IAEMOD-4035
#1035
=> IAEMOD-4035: Update tabs wrapper to allow contained wrappers to update view

libs/packages/components/src/lib/video-player/video-player.component.ts
Fixes #1048. Add constructor call that seems to add custom controls to video player
IAEMOD-5912
=> Fix to ensure that custom controls are used on video player

libs/documentation/src/lib/components/result-list/demos/template/result-list-template.component.html, libs/packages/components/src/lib/search/search.component.scss, libs/packages/sam-formly/src/lib/formly/types/checkbox.html, libs/packages/sam-formly/src/lib/formly/types/radio.html
Moved icon and content to be a part of label so that icon will move as the label text moves
IAEMOD-7310
Checkbox before:
Checkbox after:
Radio before:
Radio after:
=> IAEMOD-7310: Fix tooltip icon alignment

libs/documentation/src/lib/components/accordion/accordion.module.ts, libs/documentation/src/lib/components/accordion/demos/link-to-sb/link-to-sb.component.html, libs/documentation/src/lib/components/accordion/demos/link-to-sb/link-to-sb.component.ts, libs/documentation/src/lib/components/accordion/demos/link-to-sb/link-to-sb.module.ts, libs/documentation/src/lib/components/button-group/button-group.module.ts, libs/documentation/src/lib/components/button-group/demos/button-group-link-to-sb/button-group-link-to-sb.component.html, libs/documentation/src/lib/components/button-group/demos/button-group-link-to-sb/button-group-link-to-sb.component.ts, libs/documentation/src/lib/components/button-group/demos/button-group-link-to-sb/button-group-link-to-sb.module.ts, libs/documentation/src/lib/components/date-pipe/date-pipe.module.ts, libs/documentation/src/lib/components/date-pipe/demos/date-pipe-link-to-sb/date-pipe-link-to-sb.component.html, libs/documentation/src/lib/components/date-pipe/demos/date-pipe-link-to-sb/date-pipe-link-to-sb.component.ts, libs/documentation/src/lib/components/date-pipe/demos/date-pipe-link-to-sb/date-pipe-link-to-sb.module.ts, libs/documentation/src/lib/components/expires/demos/expires-link-to-sb/expires-link-to-sb.component.html, libs/documentation/src/lib/components/expires/demos/expires-link-to-sb/expires-link-to-sb.component.ts, libs/documentation/src/lib/components/expires/demos/expires-link-to-sb/expires-link-to-sb.module.ts, libs/documentation/src/lib/components/expires/expires.module.ts, libs/documentation/src/lib/components/external-link/demos/external-link-link-to-sb/external-link-link-to-sb.component.html, libs/documentation/src/lib/components/external-link/demos/external-link-link-to-sb/external-link-link-to-sb.component.ts, libs/documentation/src/lib/components/external-link/demos/external-link-link-to-sb/external-link-link-to-sb.module.ts, libs/documentation/src/lib/components/external-link/external-link.module.ts, libs/documentation/src/lib/components/search/demos/search-link-to-sb/search-link-to-sb.component.html, libs/documentation/src/lib/components/search/demos/search-link-to-sb/search-link-to-sb.component.ts, libs/documentation/src/lib/components/search/demos/search-link-to-sb/search-link-to-sb.module.ts, libs/documentation/src/lib/components/search/search.module.ts, libs/documentation/src/lib/components/tooltip-popover/demos/popover-link-to-sb/popover-link-to-sb.component.html, libs/documentation/src/lib/components/tooltip-popover/demos/popover-link-to-sb/popover-link-to-sb.component.ts, libs/documentation/src/lib/components/tooltip-popover/demos/popover-link-to-sb/popover-link-to-sb.module.ts, libs/documentation/src/lib/components/tooltip-popover/tooltip-popover.module.ts
Adds links from old SDS demo site to new storybook site for demos that have already been transferred. Components which have not yet been migrated will have this link added as a part of those migrations
IAEMOD-9187
=> IAEMOD-9187: Add link from old docs to Storybook

angular.json, libs/packages/components/src/lib/video-player/video-player.component.ts
In the course of adding storybook, compodoc was updated to 1.1.19. This version contains a dependency on marked 4.x.x. Somewhere between the old version and 4.x.x, marked/lib/marked.js was removed and replaced by some other formats of that file. When updating, the .cjs version was used. However, according to marked's changelong, marked/marked.min.js should be used as a drop in replacement.
Additionally, the way crossorigin is currently being set does not take into account the scenario on the first load when video has not been loaded, and so it errors.
First issues was a show-stopper, the component will not load in the current version of master.
Second issue, is more about cleaning up the console. crossorigin is applied, but that error is generated.
Crossorigin error:
=> Fix video player

.github/workflows/build-and-deploy-storybook.yml
Adds an env var to the step that is currently failing which will hopefully allow this step to succeed. Per this comment, this update should resolve the issue: https://github.com/actions/runner-images/issues/70#issuecomment-1191708172
Current github actions deployment is failing due to running out of heap space: https://github.com/GSA/sam-design-system/actions/runs/4025410379
=> Attempt to increase heap size to prevent error

libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
This pr for changing the Optional text bold to normal
https://cm-jira.usa.gov/browse/IAEMOD-9765
=> Optional label bold font removed

libs/documentation/src/lib/components/tooltip-popover/demos/tooltip-link-to-sb/tooltip-link-to-sb.component.html, libs/documentation/src/lib/components/tooltip-popover/demos/tooltip-link-to-sb/tooltip-link-to-sb.component.ts, libs/documentation/src/lib/components/tooltip-popover/demos/tooltip-link-to-sb/tooltip-link-to-sb.module.ts, libs/documentation/src/lib/components/tooltip-popover/tooltip-popover.module.ts, libs/documentation/src/lib/storybook/tooltip/tooltip-configurable/tooltip-configurable.component.html, libs/documentation/src/lib/storybook/tooltip/tooltip-configurable/tooltip-configurable.component.ts, libs/documentation/src/lib/storybook/tooltip/tooltip-configurable/tooltip-configurable.module.ts, libs/documentation/src/lib/storybook/tooltip/tooltip-introduction/tooltip-introduction.component.html, libs/documentation/src/lib/storybook/tooltip/tooltip-introduction/tooltip-introduction.component.ts, libs/documentation/src/lib/storybook/tooltip/tooltip-introduction/tooltip-introduction.module.ts, libs/documentation/src/lib/storybook/tooltip/tooltip-position/tooltip-position.component.html, libs/documentation/src/lib/storybook/tooltip/tooltip-position/tooltip-position.component.ts, libs/documentation/src/lib/storybook/tooltip/tooltip-position/tooltip-position.module.ts, libs/documentation/src/lib/storybook/tooltip/tooltip-sdsTooltip/tooltip-sdsTooltip.component.html, libs/documentation/src/lib/storybook/tooltip/tooltip-sdsTooltip/tooltip-sdsTooltip.component.ts, libs/documentation/src/lib/storybook/tooltip/tooltip-sdsTooltip/tooltip-sdsTooltip.module.ts, libs/documentation/src/lib/storybook/tooltip/tooltip.stories.ts, libs/packages/components/src/lib/tooltip/tooltip.directive.ts
Add tooltip demos to SB
Add link from SDS docs to SB
Updated tooltip to allow changes in the inputs to be reflected in tooltip without having to delete and recreate the element which the tooltip was applied. Due to how the current version of tooltip works updating an input, position for example, will not result in the position of the tooltip changing
IAEMOD-9759
=> IAEMOD-9759: Update tooltip + Add demos

libs/documentation/src/lib/components/actions/demos/basic/actions-basic.component.html, libs/documentation/src/lib/components/actions/demos/basic/actions-basic.component.ts, libs/documentation/src/lib/storybook/actions/actions-label/actions-label.component.html, libs/documentation/src/lib/storybook/actions/actions-label/actions-label.component.ts, libs/documentation/src/lib/storybook/actions/actions-label/actions-label.module.ts, libs/documentation/src/lib/storybook/actions/actions.stories.ts, libs/packages/components/src/lib/actions-menu/action-menu.model.ts, libs/packages/components/src/lib/actions-menu/actions-menu.component.html, libs/packages/components/src/lib/actions-menu/actions-menu.component.ts
This PR is for adding text and outline style for the Action Menu, this is specific to Escalation pages.
https://cm-jira.usa.gov/browse/IAEMOD-10402
=> Action menu text

libs/packages/components/package.json, libs/packages/sam-formly/package.json, libs/packages/sam-material-extensions/package.json, misc/generate-stackblitzes.ts, package-lock.json, package.json
=> Release version updated to 13.0.6

libs/documentation/src/lib/storybook/toasts/toasts-configurable/toasts-configurable.component.ts, libs/documentation/src/lib/storybook/toasts/toasts-message/toasts-message.component.ts, libs/documentation/src/lib/storybook/toasts/toasts-prevent-duplicates/toasts-prevent-duplicates.component.ts, libs/documentation/src/lib/storybook/toasts/toasts-timeout/toasts-timeout.component.ts, libs/documentation/src/lib/storybook/toasts/toasts-type/toasts-type.component.html, libs/documentation/src/lib/storybook/toasts/toasts-type/toasts-type.component.ts, libs/documentation/src/lib/storybook/toasts/toasts.stories.ts
Per demo feedback, have updated demos to use info toasts.
=> Adjust demos to use info toasts

libs/packages/sam-formly/src/lib/formly/formly.module.ts, libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
Override default material datepicker with bootstrap icon "calendar"
Resolves #1249
=> Adjust datepicker icon

libs/documentation/src/lib/storybook/dialog/dialog-alert-type/dialog-template.component.html, libs/documentation/src/lib/storybook/dialog/dialog-nested/dialog-template.component.html
Based on demo feedback, updating cancel button color
Based on demo feedback, updating cancel button color
=> Update cancel buttons

misc/generate-stackblitzes.ts
Stackblitz demos were broken in a previous version due to SAM packages used in demos not being the latest version. This PR updates the version used in stackblitz
Stackblitz demos were broken in a previous version due to SAM packages used in demos not being the latest version
=> Update sam package versions to fix stackblitz issues

libs/documentation/src/test.ts, libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.component.spec.ts, libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
This PR fixes an error where sub-steps were not being loaded. Also fixes a couple tests that were changed when this bug was introduced. And addresses one additional test issue.
Addresses #1329 
v15.0.2:
After applying this PR:
=> 1329: Fix issue with stepper

libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-introduction/rich-text-editor-introduction.component.html, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-introduction/rich-text-editor-introduction.component.ts, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-introduction/rich-text-editor-introduction.module.ts, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-max-height/rich-text-editor-max-height.component.html, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-max-height/rich-text-editor-max-height.component.ts, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-max-height/rich-text-editor-max-height.module.ts, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-min-height/rich-text-editor-min-height.component.html, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-min-height/rich-text-editor-min-height.component.ts, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor-min-height/rich-text-editor-min-height.module.ts, libs/documentation/src/lib/storybook/rich-text-editor/rich-text-editor.stories.ts, libs/documentation/src/lib/storybook/side-navigation/side-navigation-links/side-navigation-links.component.html, libs/documentation/src/lib/storybook/side-navigation/side-navigation-links/side-navigation-links.component.ts, libs/documentation/src/lib/storybook/side-navigation/side-navigation-links/side-navigation-links.module.ts, libs/documentation/src/lib/storybook/side-navigation/side-navigation.stories.ts, package-lock.json, package.json
Add demos that were missed in the transition to storybook.
This still requires an update to sam-styles before merging.
Missed some demos when moving to storybook, adding those now.
=> Add Missing Demos

libs/packages/sam-formly/src/lib/formly/types/textarea.ts
This PR is to resolve the maxLenth prop for the text area, if maxLenth not set then it's defaults to 0, so need to add the maxLenth attribute dynamically
=> Textarea maxlength

libs/documentation/src/lib/storybook/formly/formly-autocomplete/formly-autocomplete-basic/formly-autocomplete-basic.component.ts, libs/documentation/src/lib/storybook/formly/formly-autocomplete/formly-autocomplete-count/formly-autocomplete-count.component.ts, libs/documentation/src/lib/storybook/formly/formly-autocomplete/formly-autocomplete-id/formly-autocomplete-id.component.html, libs/documentation/src/lib/storybook/formly/formly-autocomplete/formly-autocomplete-id/formly-autocomplete-id.component.ts, libs/documentation/src/lib/storybook/formly/formly-autocomplete/formly-autocomplete-id/formly-autocomplete-id.module.ts, libs/documentation/src/lib/storybook/formly/formly-autocomplete/formly-autocomplete.stories.ts, libs/packages/sam-formly/src/lib/formly/types/autocomplete.ts
Setting the id field in the autocomplete fieldGroup would not cause the label and input to be connected like other inputs were. This caused an accessibility issue where clicking on the label would not result in the in autocomplete input becoming focused.
This PR:
- Adds logic so that if the SDS autocomplete does not have an ID assigned to it, it will be assigned the ID that Formly is using. This will ensure that if no ID is configured, clicking the label will focus on the auto complete.
- Adds a warning that will display if there is a mismatch between the Formly tracked ID (used in label's for field) and the Autocomplete Input ID
- Adds a demo showing how to set the ID so that the label and autocomplete input are connected. 
The new demo has three autocompletes showing the different ways …
=> 1388: Update Formly Autocomplete to make sure ID in label and Autocomplete Input match

libs/documentation/src/lib/storybook/formly/formly-input/formly-input-affix/formly-input-affix.component.ts, libs/packages/sam-formly/src/lib/formly/types/input.ts
https://github.com/GSA/sam-design-system/issues/1392
This PR is to not allowing the user to add prefix text.
=> Text prefix removed for formly input

.circleci/config.yml, libs/packages/components/src/lib/external-link/external-link.directive.ts
Update ExternalLinkDirective to allow icon to be toggled with inputs. Previously the element would have needed to be deleted and re-created to achieve this behavior. This can be tested in the external link configurable demo.
Also fixes circleCI issue preventing circleCi tests from running.
Addressed #1425
=> Allow icon to be removed without destroying directive

libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
Update logic on focusRemoved function so that item is selected and focus pushed back to autocomplete only when input is not blank and has changed.
Resolves #1420
=> Update logic on Autocomplete focusRemoved function

libs/documentation/src/lib/storybook/formly/formly-datepicker/formly-datepicker-basic/formly-datepicker-basic.component.ts, libs/packages/sam-formly/src/lib/formly/formly.module.ts
Add field to change the message displayed when datepicker has the required validator applied. If this custom field is set true AND there is something typed into the field THEN a message about an invalid format will show rather than the field is required error message.
Addresses #1427
=> Add property for additional message when required validator applied to type=datepicker

libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/custom-stepper.component.html, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/custom-stepper.component.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/formly-stepper-advanced.component.html, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/formly-stepper-advanced.component.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/formly-stepper-advanced.module.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/stepper-advanced.service.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/subawardee.component.html, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/subawardee.component.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-basic/formly-stepper-basic-uneven.component.html, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-basic/formly-stepper-basic-uneven.component.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-basic/formly-stepper-basic.component.html, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-basic/formly-stepper-basic.component.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-basic/formly-stepper-basic.module.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-introduction/formly-stepper-introduction.component.html, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-introduction/formly-stepper-introduction.component.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-introduction/formly-stepper-introduction.module.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-uswds/formly-stepper-uswds-custom.component.html, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-uswds/formly-stepper-uswds-custom.component.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-uswds/formly-stepper-uswds.component.html, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-uswds/formly-stepper-uswds.component.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-uswds/formly-stepper-uswds.module.ts, libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper.stories.ts
added the stepper demo to storybook
=> Sb stepper

libs/packages/components/package.json, libs/packages/sam-formly/package.json
Adding popper.js peer dep to sds-components and sds-formly packages. Not including in material-extensions as neither popover nor tooltip are used in that package.
Peer dep needed to ensure that teams have popper.js installed to avoid errors
=> Add popper peer dep to packages

libs/documentation/src/lib/storybook/formly/formly-filter/formly-filter-horizontal/formly-filter-horizontal.component.html, libs/packages/components/src/lib/popover/popover.scss, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html, libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
Change structure of horizontal filters to allow formly forms being used for filters to appear in new popover. Also made a few changes to the popover configuration to address bugs found during testing.
During demo it was initially noted that certain filters in the horizontal filters were not displaying.
=> Fix Filters In Horizontal Filters

libs/documentation/src/lib/storybook/formly/formly-filter/formly-filter-horizontal/formly-filter-horizontal.component.ts, libs/documentation/src/lib/storybook/formly/formly-filter/formly-filter-introduction/formly-filter-introduction.component.html, libs/documentation/src/lib/storybook/formly/formly-filter/formly-filter-introduction/formly-filter-introduction.component.ts, libs/packages/components/package.json, libs/packages/sam-formly/package.json, libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html, libs/packages/sam-material-extensions/package.json, package-lock.json, package.json
Update condition to not render field if label is not present.
Add documentation to explain changes to horizontal filter configs caused by 17.0.7-.9
With the latest popover changes FormlyFieldConfig parsing has changed requiring that each top-level FormlyFieldConfig contain a label to display on the toolbar. This change continues to enforces that without causing breaking console errors.
=> Add Condition To Prevent Horizontal Filter Without Label

libs/packages/sam-formly/src/lib/formly/types/input.ts
Making input field as dirty when clear text using the 'x' button
=> Marked as dirty after clearing the input value

libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/custom-stepper.component.html, libs/packages/sam-formly/src/lib/formly-stepper/sds-step-buttons.ts, libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
Add input `canReviewWithErrors` which allows the user to navigate to Review step even if there are unresolved errors.
Resolves #1536
=> 1536 entity registration modules mvp stepper always enable review page even if there are formly errors

libs/packages/components/src/lib/tree-table/tree-table.component.html
Update roles in tree-table to pass ARIA 1.1 check performed by AMP. If testing standard updates to ARIA 1.2 or greater then posinset is a valid property of the row role.
Resolves #1160 
Passing AMP test:
=> Update roles in tree-table to pass ARIA1.1 check

libs/documentation/src/lib/storybook/button-group/button-group-modular/button-group-modular.component.html, libs/documentation/src/lib/storybook/button-group/button-group-modular/button-group-modular.component.ts, libs/documentation/src/lib/storybook/button-group/button-group-modular/button-group-modular.module.ts, libs/documentation/src/lib/storybook/button-group/button-group.stories.ts, libs/packages/sam-material-extensions/src/lib/button-group/button-group.component.html, libs/packages/sam-material-extensions/src/lib/button-group/button-group.component.ts, package-lock.json, package.json
Add input modularDashboard which provides for different styling based on latest mockups.
Add demos to show new appearance.
Waiting on [sam-styles #711](https://github.com/GSA/sam-styles/pull/711)
Resolves #1520.
=> Add input to button-group to support modular dashboard
