GSA/sam-design-system

- .circleci/config.yml
- angular.json
Fix angular.json references; add circleci config
> Add CircleCi

- .circleci/config.yml
- apps/sam-design-system-site/src/app/app.component.html
- apps/sam-design-system-site/src/styles.scss
- karma.conf.js
- package-lock.json
- package.json
Adds sam-styles to sam-design-system-site also updates home page with new styles
> Adding styles and updating home page

- libs/packages/components/src/lib/accordion/index.ts
- libs/packages/components/src/lib/accordion/public-api.ts
- libs/packages/components/src/lib/page/index.ts
- libs/packages/components/src/lib/page/public-api.ts
- libs/packages/components/src/lib/public-api.ts
- libs/packages/components/src/lib/toolbar/index.ts
- libs/packages/components/src/lib/toolbar/public-api.ts
Remove barrel files from library components
> Remove barrel files from components

- apps/sam-design-system-site/src/styles.scss
- package-lock.json
- package.json
Move component scss to sam-styles package
> Move component scss to sam-styles package

- README.md
- tools/scripts/pack-and-publish.js
- tools/scripts/update-libs-version.js
Fix publish scripts & intructions
> Fix publish scripts 

- apps/sam-design-system-site/src/styles.scss
- libs/packages/components/src/lib/pagination/pagination.component.html
> Add pagination styles

- apps/sam-design-system-site/src/styles.scss
- libs/packages/components/src/lib/pagination/pagination.component.html
- package-lock.json
- package.json
> Update to pagination UI

- libs/packages/components/src/lib/icon/index.ts
Fix icon import by declaring "IconDefinition" type
> Fix icon import

- libs/component-sample/src/lib/feature/toolbar-sample/toolbar-sample.component.html
- libs/packages/components/src/lib/accordion/accordion-item-header.component.html
- libs/packages/components/src/lib/accordion/accordion-item-header.component.ts
- libs/packages/components/src/lib/accordion/accordion-item.component.html
- libs/packages/components/src/lib/accordion/accordion-item.component.ts
- libs/packages/components/src/lib/accordion/accordion.directive.ts
- libs/packages/components/src/lib/toolbar/toolbar-header.component.html
- libs/packages/components/src/lib/toolbar/toolbar-header.component.ts
- libs/packages/components/src/lib/toolbar/toolbar.component.html
- libs/packages/components/src/lib/toolbar/toolbar.component.ts
- package-lock.json
- package.json
Update markup to replace 'sam' prefix with 'sds'
> Update markup to replace 'sam' prefix with 'sds'

- libs/component-sample/src/lib/feature/pagination-sample/pagination-sample.component.html
- libs/component-sample/src/lib/feature/pagination-sample/pagination-sample.component.ts
- libs/packages/components/src/lib/pagination/model/paginationModel.ts
- libs/packages/components/src/lib/pagination/pagination.component.html
- libs/packages/components/src/lib/pagination/pagination.component.spec.ts
- libs/packages/components/src/lib/pagination/pagination.component.ts
> Iae 18665 Pagination

- libs/packages/components/src/lib/accordion/accordion-item.component.spec.ts
> Test for accordion item

- .circleci/config.yml
- apps/sam-design-system-site/src/app/app.component.html
- libs/component-sample/src/lib/component-sample.module.ts
- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.html
- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.ts
- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.module.ts
- libs/component-sample/src/lib/feature/toolbar-sample/toolbar-sample.component.html
- libs/packages/components/src/lib/public-api.ts
- libs/packages/components/src/lib/side-navigation/model/side-navigation-model.ts
- libs/packages/components/src/lib/side-navigation/side-navigation.component.html
- libs/packages/components/src/lib/side-navigation/side-navigation.component.spec.ts
- libs/packages/components/src/lib/side-navigation/side-navigation.component.ts
- libs/packages/components/src/lib/side-navigation/side-navigation.module.ts
> IAE-19504 add side navigation component

- apps/sam-design-system-site/src/app/app.component.html
- libs/component-sample/src/lib/component-sample.module.ts
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.html
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.ts
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data2.component.html
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data2.component.ts
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample.component.html
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample.component.ts
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample.module.ts
- libs/packages/components/src/lib/public-api.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.spec.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.module.ts
> IAE 19413 add Search Result List

- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.html
- libs/packages/components/src/lib/icon/index.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.scss
- package-lock.json
Styling the entity results list 
IAE-19965
> IAE-19965 Search list

- tsconfig.json
> update build components for layout

- libs/component-sample/src/lib/feature/footer-sample/footer-sample.component.ts
- libs/packages/components/src/lib/footer/footer.component.html
- libs/packages/components/src/lib/footer/model/FooterModel.ts
- package-lock.json
- package.json
> Replace logo with background image

- libs/component-sample/src/lib/feature/subheader-sample/subheader-sample.component.html
- libs/component-sample/src/lib/feature/subheader-sample/subheader-sample.component.ts
- libs/component-sample/src/lib/feature/subheader-sample/subheader-sample.module.ts
- libs/packages/layouts/src/lib/feature/subheader/subheader-actions.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader-buttons.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader-search.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader.component.ts
- libs/packages/layouts/src/lib/feature/subheader/subheader.module.ts
- libs/packages/layouts/src/lib/public-api.ts
- libs/packages/layouts/tslint.json
> Adding subheader layout component

- libs/packages/layouts/src/lib/feature/subheader/subheader.component.html
> Add grid container to subheader

- libs/packages/layouts/src/lib/feature/subheader/subheader.component.html
> Fix subheader title alignment

- libs/layout-sample/src/lib/feature/search-list/search-list-sample.component.html
- libs/layout-sample/src/lib/feature/search-list/search-list-sample.component.ts
- libs/layout-sample/src/lib/feature/search-list/search-list-sample.module.ts
- libs/packages/components/src/lib/page/page.component.ts
- package-lock.json
> Clean up of search results layout custom page

- libs/component-sample/src/lib/feature/side-menu-filters-sample/side-menu-filters-sample.component.html
- libs/component-sample/src/lib/feature/side-menu-filters-sample/side-menu-filters-sample.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> IAE-19418 filter output added

- libs/component-sample/src/lib/feature/icon-sample/icon-sample.component.html
- libs/component-sample/src/lib/feature/icon-sample/icon-sample.component.ts
- libs/packages/components/src/lib/icon/index.ts
- package-lock.json
IAE-18673
Add the the icon svgs onto the sam-styles and sam design repo
IAE-18673
> IAE-18673 Icons library

- apps/sam-design-system-site/src/app/app.component.html
- libs/component-sample/src/lib/component-sample.module.ts
- libs/component-sample/src/lib/feature/dialog-sample/dialog-overview-example-dialog.html
- libs/component-sample/src/lib/feature/dialog-sample/dialog-sample.component.html
- libs/component-sample/src/lib/feature/dialog-sample/dialog-sample.component.ts
- libs/component-sample/src/lib/feature/dialog-sample/dialog-sample.module.ts
- libs/packages/components/src/lib/dialog/dialog-animations.ts
- libs/packages/components/src/lib/dialog/dialog-config.ts
- libs/packages/components/src/lib/dialog/dialog-container.component.ts
- libs/packages/components/src/lib/dialog/dialog-content.directives.ts
- libs/packages/components/src/lib/dialog/dialog-ref.ts
- libs/packages/components/src/lib/dialog/dialog.module.ts
- libs/packages/components/src/lib/dialog/dialog.spec.ts
- libs/packages/components/src/lib/dialog/dialog.ts
- libs/packages/components/src/lib/public-api.ts
> Add dialog component and sample page

- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.html
- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.ts
- libs/packages/components/src/lib/common-navigation/common-navigation-model.ts
- libs/packages/components/src/lib/side-navigation/model/side-navigation-model.ts
- libs/packages/components/src/lib/side-navigation/side-navigation.component.html
- libs/packages/components/src/lib/side-navigation/side-navigation.component.spec.ts
- libs/packages/components/src/lib/side-navigation/side-navigation.component.ts
- libs/packages/components/src/lib/toolbar/toolbar-expand.directive.ts
> IAE-21640 side navigation enhancement

- package-lock.json
- package.json
> styles version update

- package-lock.json
- package.json
> styles update

- package-lock.json
- package.json
> Update sam-styles to 0.0.26

- libs/packages/components/src/lib/header/header.component.html
- libs/packages/components/src/lib/header/header.component.ts
> hide top banner

- apps/sam-design-system-site/src/app/app.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
- libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts
- libs/sam-formly-sample/src/lib/feature/formly-sample/formly-input.component.ts
- package-lock.json
> IAE-22724 debounce time issue for formly autocomplete

- .gitignore
> Ignore vscode editor files

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
- libs/packages/components/src/lib/autocomplete-search/models/SDSAutocompleteConfiguration.ts
- libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts
> IAE-22397 adding free text into autocomplete

- libs/component-sample/src/lib/feature/actions-menu-sample/actions-menu-sample.component.ts
- libs/packages/layouts/src/lib/feature/actions-menu/actions-menu.component.html
> Adds config to change trigger class in actions menu

- libs/component-sample/src/lib/feature/side-menu-filters-sample/side-menu-filters-sample.component.html
> side menu filter sample changes

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
- libs/packages/components/src/lib/autocomplete-search/models/SDSAutocompleteConfiguration.ts
- libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts
- libs/packages/components/src/lib/selected-result/selected-result.component.html
- libs/packages/components/src/lib/selected-result/selected-result.component.spec.ts
- libs/packages/components/src/lib/selected-result/selected-result.component.ts
> Autocomplete enhancements

- CODEOWNERS
> Create Code Owners File

- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.html
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.ts
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample.component.html
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample.module.ts
- libs/layout-sample/src/lib/feature/search-list-layout/search-list-layout-sample.component.html
- libs/layout-sample/src/lib/feature/search-list-layout/search-list-layout-sample.component.ts
- libs/layout-sample/src/lib/feature/search-list/search-list-sample.component.html
- libs/layout-sample/src/lib/ui/search-result-list-sample-data/search-list-event-sample.module.ts
- libs/layout-sample/src/lib/ui/search-result-list-sample-data/search-result-list-sample-data.component.html
- libs/layout-sample/src/lib/ui/search-result-list-sample-data/search-result-list-sample-data.component.ts
- libs/packages/components/src/lib/pagination/pagination.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
- libs/packages/layouts/src/lib/feature/actions-menu/actions-menu.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
> IAE-23322 Results list updates

- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.html
- libs/layout-sample/src/lib/feature/search-list/search-list-sample.component.html
- libs/layout-sample/src/lib/ui/search-result-list-sample-data/search-result-list-sample-data.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
- package-lock.json
- package.json
> Updated to match sam-styles adjustments

- apps/sam-design-system-site/src/app/app.module.ts
- libs/component-sample/src/lib/feature/header-sample/header-sample.component.ts
> Update header to use base href path

- libs/packages/components/src/lib/menu/menu-header.component.html
- libs/packages/components/src/lib/menu/menu-item.component.ts
- libs/packages/layouts/src/lib/feature/actions-menu/actions-menu.component.html
> Menu component ui updates

- angular.json
- libs/packages/components/src/lib/header/header.component.html
- libs/packages/components/src/lib/header/header.component.spec.ts
- libs/packages/components/src/lib/header/header.component.ts
- libs/packages/components/src/lib/header/header.module.ts
- libs/packages/components/src/lib/top-banner/top-banner.component.html
- libs/packages/components/src/lib/top-banner/top-banner.component.ts
> Remove uswds js dependency

- libs/component-sample/src/lib/feature/subheader-sample/subheader-sample.component.html
- libs/component-sample/src/lib/feature/subheader-sample/subheader-sample.module.ts
- libs/packages/layouts/src/lib/feature/subheader/subheader-actions.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader-buttons.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader-drawer.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader-search.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader.component.html
- libs/packages/layouts/src/lib/feature/subheader/subheader.component.ts
- libs/packages/layouts/src/lib/feature/subheader/subheader.module.ts
> Subheader UI updates

- apps/sam-design-system-site/src/styles.scss
- libs/packages/sam-formly/src/lib/formly/formly.config.ts
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
- libs/packages/sam-formly/src/lib/formly/types/datepicker.spec.ts
- libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.component.ts
- package.json
> IAE-25130 Adding material datepicker

- libs/component-sample/src/lib/feature/actions-menu-sample/actions-menu-sample.component.html
- libs/component-sample/src/lib/feature/actions-menu-sample/actions-menu-sample.component.ts
- libs/packages/components/src/lib/menu/menu-item.component.ts
- libs/packages/components/src/lib/menu/menu.component.html
- libs/packages/components/src/lib/menu/menu.component.ts
- libs/packages/layouts/src/lib/feature/actions-menu/actions-menu.component.html
- libs/packages/layouts/src/lib/feature/actions-menu/actions-menu.component.ts
- package-lock.json
> Actions menu sync

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Updating to sds version to 0.6.1

- libs/packages/sam-formly/package.json
> add material dependency

- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.wrapper.ts
> move error message

- package-lock.json
- package.json
> build: get latest minor and patch version of sam-styles

- libs/packages/sam-formly/src/lib/formly/formly.module.ts
> IAE-27463 Invalid Date format

- libs/layout-sample/src/lib/feature/search-list-layout/search-list-layout-sample.component.html
- libs/layout-sample/src/lib/feature/search-list/search-list-sample.component.html
- libs/packages/components/src/lib/toolbar/toolbar-expand.directive.ts
- libs/packages/components/src/lib/toolbar/toolbar.component.ts
https://cm-jira.usa.gov/browse/IAE-27466
https://cm-jira.usa.gov/browse/IAE-27465
Actions (Type . to access issue actions)
> toolbar fix

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> back merge  Autocomplete from sam-ui-elements

- libs/packages/components/src/lib/selected-result/selected-result.component.html
> IAE-27479 auto complete chip color changes

- libs/component-sample/src/lib/feature/side-menu-filters-sample/side-menu-filters-sample.component.html
- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.html
- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.ts
- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.module.ts
- libs/packages/components/src/lib/selected-result/selected-result.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> IAE-27631 accordion removed from sds-filter

- apps/sam-design-system-site/src/styles.scss
> date picker colors

- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.spec.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.module.ts
- package-lock.json
- package.json
> no results

- libs/packages/components/src/lib/search-result-list/search-result-list.module.ts
> Fix: removed icon library from the constructor

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version 0.6.2

- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.component.html
- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.component.ts
- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.module.ts
> Input box-Missing form label sample added

- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.component.html
- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.component.ts
> Formly wrapper name changes

- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.html
- libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.ts
- libs/packages/components/src/lib/accordion/accordion-item-header.component.html
- libs/packages/components/src/lib/accordion/accordion-item-header.component.scss
- libs/packages/components/src/lib/accordion/accordion-item-header.component.ts
JIRA TICKET - IAE 27970 
Added code samples for three Side Navigation use cases:
- Side Nav without a title but with a functional accordion toggle
- Side Nav with a tile but without accordion functionality (expanded)
- Side Nav without a title or accordion functionality (expanded)
- [] Internet Explorer 11
> Side navigation header options added

- apps/sam-design-system-site/browserslist
- apps/sam-design-system-site/src/styles.scss
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.html
- libs/layout-sample/src/lib/feature/search-list/search-list-sample.component.html
- libs/layout-sample/src/lib/ui/search-result-list-sample-data/search-result-list-sample-data.component.html
- libs/packages/components/src/lib/pagination/pagination.component.html
Autoprefixer to include IE10/11 and grid autoplace
Fixes for result lists
> IE 11 fixes

- package-lock.json
- package.json
> version 0.6.3

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> bump to 0.6.5 - all packages

- libs/sam-formly-sample/src/lib/feature/formly-forms/formly-forms.component.html
> Form styles added

- libs/packages/components/src/lib/selected-result/selected-result.component.html
> IAE-29063 Updated Aria label for the remove item

- package-lock.json
- package.json
> bump sam styles to 0.0.51

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
- package.json
> Timeout issue for formly

- package-lock.json
- package.json
> bump sam-styles to v0.0.52

- libs/component-sample/src/lib/feature/search-result-list-sample/result-list-child.component.html
- libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.html
- libs/layout-sample/src/lib/ui/search-result-list-sample-data/search-result-list-sample-data.component.html
> modify result listings sample to include new coding for status tags

- libs/component-sample/src/lib/feature/collapse-sample/collapse-sample.module.ts
- libs/packages/components/src/lib/public-api.ts
> Update for collapse changes

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> auto complete model change fix

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to 0.6.8

- libs/layout-sample/src/lib/feature/search-list/search-list-sample.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
> pagination and sort hidden when no results

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/models/SDSAutocompleteConfiguration.ts
- libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts
- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.component.html
- package.json
> IAE-31544 aria-label text configurable changes

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> IAE-31964 Selection mode issue fix

- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> search results changes

- package.json
> bump sam-styles to v0.0.56

- package.json
> bump sam styles to 0.0.57

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> Changes to Autocomplete free text search and fix scrolling

- libs/packages/components/src/lib/video-player/js/px-video.js
> Fixed the issue for full screen in IE

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> updated selectionmode issue

- package.json
> Updated sam-style v0.0.58

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.accordian.ts
- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.component.ts
> added options and expand is configurable

- angular.json
Changed the order of the projects.. this is causing the issue in building the libs packing.
> changed the order of the projects

- apps/sam-design-system-site/src/assets/video/gsa-sample.vtt
- libs/documentation/src/lib/components/video/demos/basic/video-player-sample-data.ts
> Update video player sample to have GSA video and caption file

- package.json
> sam-style version updated

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> revert history changes

- libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
> show error message on blur, for autocompletes

- libs/packages/sam-formly/tsconfig.lib.json
> updating compiler option to fix the build issue

- libs/packages/sam-formly/src/lib/formly/formly.validators.ts
> Added a custom validator for autocompletes

- libs/documentation/src/lib/components/video/demos/basic/video-player-sample-data.ts
> Video player caption path change

- libs/packages/components/src/lib/video-player/video-player.component.ts
> Update captions to be off by default.

- apps/sam-design-system-site/src/app/app.component.html
- libs/documentation/src/lib/apidoc/components/components.ts
- libs/documentation/src/lib/apidoc/components/documentation.json
- libs/documentation/src/lib/components/formly/autocomplete/demos/basic/autocomplete-basic.component.html
- libs/documentation/src/lib/components/formly/autocomplete/demos/basic/autocomplete-basic.component.ts
- libs/documentation/src/lib/components/shared/source-page/source.component.ts
- libs/documentation/src/lib/components/text/demos/basic/text-basic.component.html
- libs/documentation/src/lib/components/text/demos/basic/text-basic.component.ts
- libs/documentation/src/lib/components/text/demos/basic/text-basic.module.ts
- libs/documentation/src/lib/components/text/text.module.ts
- libs/documentation/src/lib/documentation.module.ts
- libs/packages/components/src/lib/autocomplete/autocomplete.component.html
- libs/packages/components/src/lib/autocomplete/autocomplete.component.spec.ts
- libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
- libs/packages/components/src/lib/public-api.ts
- libs/packages/components/src/lib/selected-result/models/sds-selectedItem.model.ts
- libs/packages/components/src/lib/text/child.component.ts
- libs/packages/components/src/lib/text/text.component.ts
- libs/packages/components/src/lib/text/text.module.ts
- libs/packages/sam-formly/src/lib/formly/formly.config.ts
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
- libs/packages/sam-formly/src/lib/formly/types/text.ts
Update autocomplete to be compatible with Formly and change detection.
> AutoComplete Formly and CD fixes

- libs/packages/sam-formly/src/lib/formly/formly.validators.ts
> Autocomplete validation changes

- libs/packages/components/src/lib/external-link/external-link.directive.ts
> external link super script changes

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Update version to 0.6.13

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.ts
- libs/documentation/src/lib/components/result-list/demos/card/result-list-card-component.component.ts
- libs/documentation/src/lib/components/result-list/demos/component/result-list-component.component.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
- libs/packages/components/src/lib/video-player/video-player.component.ts
I created information messages for the search results page. I did this by changing the existing data structure in the result list sample component to an object of arrays and adding two additional data structures: an additional object of arrays and an object. I added additional logic to the template for the new options (Empty List & Error Message) in the Search Result List Template.
IAE-31069
- [X ] Chrome
> IAE 31069- Create a configurable info message section for search

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> Autocomplete dropdown with configurable input readonly

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> added change detection to formly init

- apps/sam-design-system-site/src/app/app.component.html
- libs/documentation/src/lib/components/formly/search/demos/basic/search-basic.component.html
- libs/documentation/src/lib/components/formly/search/demos/basic/search-basic.component.ts
- libs/documentation/src/lib/components/formly/search/demos/basic/search-basic.module.ts
- libs/documentation/src/lib/components/formly/search/demos/optional/search-optional.component.html
- libs/documentation/src/lib/components/formly/search/demos/optional/search-optional.component.ts
- libs/documentation/src/lib/components/formly/search/demos/optional/search-optional.module.ts
- libs/documentation/src/lib/components/formly/search/search.module.ts
- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.html
- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
- libs/documentation/src/lib/components/search/demos/basic/search-basic.module.ts
- libs/documentation/src/lib/components/search/demos/optional/search-optional.component.html
- libs/documentation/src/lib/components/search/demos/optional/search-optional.component.ts
- libs/documentation/src/lib/components/search/demos/optional/search-optional.module.ts
- libs/documentation/src/lib/components/search/search.module.ts
- libs/documentation/src/lib/components/text/demos/basic/text-basic.component.ts
- libs/documentation/src/lib/documentation.module.ts
- libs/packages/components/src/lib/public-api.ts
- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.ts
- libs/packages/components/src/lib/search/search.module.ts
- libs/packages/components/src/lib/search/search.spec.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.spec.ts
- libs/packages/sam-formly/src/lib/formly/formly.config.ts
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
- libs/packages/sam-formly/src/lib/formly/types/search.spec.ts
- libs/packages/sam-formly/src/lib/formly/types/search.ts
- package-lock.json
- package.json
> Search formly

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> updated emit on refresh

- apps/sam-design-system-site/src/styles.scss
- libs/documentation/src/lib/components/shared/examples-page/demo.component.html
> Update demo with new card styles

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> change detection added

- libs/documentation/src/lib/components/sidenavigation/demos/optional/navigate.config.ts
- libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.html
- libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.ts
- libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.module.ts
- libs/documentation/src/lib/components/sidenavigation/sidenavigation.module.ts
> Side nav on sis filter refresh

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> SDS release 0.6.14

- package.json
> Update package.json bump sam-styles to 0.0.67

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> removed event

- libs/documentation/src/lib/components/formly/search/demos/basic/search-basic.component.ts
- libs/documentation/src/lib/components/search/demos/optional/search-optional.component.html
- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.ts
- libs/packages/components/src/lib/search/search.spec.ts
> model updated

- CODEOWNERS
> Add new angular devs

- apps/sam-design-system-site/src/app/app.component.html
- apps/sam-design-system-site/src/material.theme.scss
- apps/sam-design-system-site/src/styles.scss
- libs/documentation/src/lib/components/groupwrappers/demos/basic/accordiongroup-basic.component.html
- libs/documentation/src/lib/components/groupwrappers/demos/basic/accordiongroup-basic.component.ts
- libs/documentation/src/lib/components/groupwrappers/demos/basic/accordiongroup-basic.module.ts
- libs/documentation/src/lib/components/groupwrappers/groupwrappers.module.ts
- libs/documentation/src/lib/documentation.module.ts
- libs/packages/sam-formly/src/lib/formly/formly.config.ts
- libs/packages/sam-formly/src/lib/formly/sds-formly-options.ts
- libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
> Documentation  group options

- libs/documentation/src/lib/components/formly/datepicker/closing.md
- libs/documentation/src/lib/components/formly/datepicker/datepicker.module.ts
- libs/documentation/src/lib/components/formly/datepicker/demos/basic/datepicker-basic.component.html
- libs/documentation/src/lib/components/formly/datepicker/demos/basic/datepicker-basic.component.ts
- libs/documentation/src/lib/components/formly/datepicker/demos/basic/datepicker-basic.module.ts
- libs/documentation/src/lib/components/formly/datepicker/demos/daterange/datepicker-daterange.component.html
- libs/documentation/src/lib/components/formly/datepicker/demos/daterange/datepicker-daterange.component.ts
- libs/documentation/src/lib/components/formly/datepicker/demos/daterange/datepicker-daterange.module.ts
- libs/documentation/src/lib/components/formly/datepicker/demos/validation/datepicker-validation.component.html
- libs/documentation/src/lib/components/formly/datepicker/demos/validation/datepicker-validation.component.ts
- libs/documentation/src/lib/components/formly/datepicker/demos/validation/datepicker-validation.module.ts
> documentation for date added

- libs/documentation/src/lib/components/shared/api-page/docs-api-component.component.ts
> Fix wrappers for non form control formly components

- libs/documentation/src/lib/components/filters/demos/basic/filters-basic.component.html
- libs/documentation/src/lib/components/filters/demos/basic/filters-basic.component.ts
- libs/documentation/src/lib/components/filters/demos/basic/filters-basic.module.ts
> Removed text area from filters

- apps/sam-design-system-site/src/app/app.component.html
- libs/documentation/src/lib/components/descriptionwrapper/demos/basic/descriptionwrapper-basic.component.html
- libs/documentation/src/lib/components/descriptionwrapper/demos/basic/descriptionwrapper-basic.component.ts
- libs/documentation/src/lib/components/descriptionwrapper/demos/basic/descriptionwrapper-basic.module.ts
- libs/documentation/src/lib/components/descriptionwrapper/descriptionwrapper.module.ts
- libs/documentation/src/lib/components/labelwrapper/demos/basic/labelwrapper-basic.component.html
- libs/documentation/src/lib/components/labelwrapper/demos/basic/labelwrapper-basic.component.ts
- libs/documentation/src/lib/components/labelwrapper/demos/basic/labelwrapper-basic.module.ts
- libs/documentation/src/lib/components/labelwrapper/labelwrapper.module.ts
- libs/documentation/src/lib/components/validationwrapper/demos/basic/validationwrapper-basic.component.html
- libs/documentation/src/lib/components/validationwrapper/demos/basic/validationwrapper-basic.component.ts
- libs/documentation/src/lib/components/validationwrapper/demos/basic/validationwrapper-basic.module.ts
- libs/documentation/src/lib/components/validationwrapper/validationwrapper.module.ts
- libs/documentation/src/lib/documentation.module.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.accordian.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.filterwrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/validation.wrapper.ts
> Label, Description, Validation Wrappers documentation added

- libs/documentation/src/lib/components/filters/demos/basic/filters-basic.component.html
- libs/documentation/src/lib/components/filters/demos/basic/filters-basic.component.ts
- libs/sam-formly-sample/src/lib/feature/filter-wrapper/filter-wrapper.component.html
> Removed search from Filter demo and History configuration demo changes

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version 0.6.15

- libs/documentation/src/lib/components/filters/demos/config/filter-config.component.html
- libs/documentation/src/lib/components/filters/demos/config/filter-config.module.ts
> More filter demo added

- libs/documentation/src/lib/components/groupwrappers/groupwrappers.module.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
> Update logic to hide label wrapper for formly-groups

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Updating version to 0.6.16

- apps/sam-design-system-site/src/app/app.component.html
- libs/documentation/src/lib/components/templateoptions/demos/announceLabel/templateoption-announceLabel.component.html
- libs/documentation/src/lib/components/templateoptions/demos/announceLabel/templateoption-announceLabel.component.ts
- libs/documentation/src/lib/components/templateoptions/demos/announceLabel/templateoption-announceLabel.module.ts
- libs/documentation/src/lib/components/templateoptions/demos/basic/templateoptions-basic.component.html
- libs/documentation/src/lib/components/templateoptions/demos/basic/templateoptions-basic.component.ts
- libs/documentation/src/lib/components/templateoptions/demos/basic/templateoptions-basic.module.ts
- libs/documentation/src/lib/components/templateoptions/demos/expand/templateoption-expand.component.html
- libs/documentation/src/lib/components/templateoptions/demos/expand/templateoption-expand.component.ts
- libs/documentation/src/lib/components/templateoptions/demos/expand/templateoption-expand.module.ts
- libs/documentation/src/lib/components/templateoptions/demos/hideOptional/templateoption-hideOptional.component.html
- libs/documentation/src/lib/components/templateoptions/demos/hideOptional/templateoption-hideOptional.component.ts
- libs/documentation/src/lib/components/templateoptions/demos/hideOptional/templateoption-hideOptional.module.ts
- libs/documentation/src/lib/components/templateoptions/demos/tags/templateoption-tags.component.html
- libs/documentation/src/lib/components/templateoptions/demos/tags/templateoption-tags.component.ts
- libs/documentation/src/lib/components/templateoptions/demos/tags/templateoption-tags.module.ts
- libs/documentation/src/lib/components/templateoptions/templateoptions.module.ts
- libs/documentation/src/lib/documentation.module.ts
> Documentation added for custom formly template options. 

- libs/packages/components/src/lib/search/search.component.ts
> search console error changes

- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.html
- libs/documentation/src/lib/components/search/demos/optional/search-optional.component.html
> Updated documentation for the SDS search

- libs/documentation/src/lib/components/video/video.module.ts
> Updated closing notes path for the Videoplayer

- libs/documentation/src/lib/components/formly/autocomplete/autocomplete.module.ts
- libs/documentation/src/lib/components/formly/checkbox/checkbox.module.ts
- libs/documentation/src/lib/components/formly/datepicker/datepicker.module.ts
- libs/documentation/src/lib/components/formly/input/input.module.ts
- libs/documentation/src/lib/components/formly/multicheckbox/multicheckbox.module.ts
- libs/documentation/src/lib/components/formly/radio/radio.module.ts
- libs/documentation/src/lib/components/formly/search/search.module.ts
- libs/documentation/src/lib/components/formly/select/select.module.ts
> git hub file path updated

- CHANGELOG.md
- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to  0.6.17

- libs/documentation/src/lib/components/groupwrappers/groupwrappers.module.ts
> github path updated

- libs/documentation/src/lib/pages/introduction/introduction.component.html
> Fix intro page styling for code anchors

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
- libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
- libs/packages/components/src/lib/selected-result/selected-result.component.html
Autocomplete duplicate model issue
When no results on enter event is adding Item issue fixed
Hide x mark on chip when disabled
> autocomplete duplicate issue, highlight enter event changes

- apps/sam-design-system-site/src/styles.scss
- libs/documentation/src/lib/shared/component-wrapper/component-wrapper.component.html
> Fix tab buttons

- libs/packages/components/src/lib/video-player/video-player.component.html
- libs/packages/components/src/lib/video-player/video-player.component.ts
> added crossorigin input

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to 0.6.19

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.ts
- libs/packages/components/src/lib/search-result-list/model/search-results.model.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.spec.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
> Search results configurable model

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release version 0.6.20

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to 0.6.21

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.ts
> update the text for search results

- package-lock.json
- package.json
Update sam-styles from v0.0.67 to v0.0.77
> updated sam-styles to v0.0.77

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.ts
- libs/documentation/src/lib/components/result-list/demos/template/result-list-template.component.html
- libs/documentation/src/lib/components/result-list/demos/template/result-list-template.component.ts
- libs/documentation/src/lib/components/result-list/demos/template/result-list-template.module.ts
- libs/documentation/src/lib/components/result-list/result-list.module.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
> Search results with custom template for no results

- libs/documentation/src/lib/components/shared/examples-page/demo.component.html
- libs/documentation/src/lib/shared/component-wrapper/component-wrapper.component.html
> Fix card body padding and module heading style

- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.scss
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
- package-lock.json
- package.json
> Multi checkbox css updated in sam-style version 0.0.79

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release version to 0.6.22

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Releasing version 0.6.23

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
> Auto complete length check changes

- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.html
- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
> added example for search model change

- libs/documentation/src/lib/pages/layout/layout.component.html
- package-lock.json
- package.json
Update Sam Styles dependency 
Update Sam Styles to v0.0.81
> Sam styles@v0.0.81

- libs/component-sample/src/lib/feature/subheader-sample/subheader-sample.component.html
- libs/documentation/src/lib/components/subheader/demos/basic/subheader-basic.component.html
Add class to style navbar title and stop using H1 which is semantically incorrect
> add navbar title

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Updated Packages to 0.6.24

- libs/documentation/src/lib/components/filters/demos/config/fields.ts
- libs/documentation/src/lib/components/filters/demos/config/filter-config.component.ts
- libs/documentation/src/lib/components/filters/demos/hideexpression/filters-hideexpression.component.html
- libs/documentation/src/lib/components/filters/demos/hideexpression/filters-hideexpression.component.ts
- libs/documentation/src/lib/components/filters/demos/hideexpression/filters-hideexpression.module.ts
- libs/documentation/src/lib/components/filters/filters.module.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.spec.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> Hide expression changes

- libs/documentation/src/lib/components/download/download.module.ts
> Formly document url updated

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
- libs/documentation/src/lib/components/result-list/demos/card/card-item/card-item.component.html
- libs/documentation/src/lib/components/result-list/demos/card/result-list-card-component.component.html
- libs/documentation/src/lib/components/result-list/demos/component/result-list-component.component.html
- libs/documentation/src/lib/pages/layout/layout.component.html
- libs/packages/components/src/lib/pagination/pagination.component.html
- libs/packages/components/src/lib/pagination/pagination.component.scss
- libs/packages/components/src/lib/pagination/pagination.component.ts
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Fixed firefox issue with line height
Fixed page number input to be dynamic width
Fixed condensed result list in demos
Fixed result list card layout margin issues
> Update pagination to show total results

- libs/packages/components/src/lib/external-link/external-link.directive.ts
> External link fix

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
- libs/documentation/src/lib/components/result-list/demos/card/card-item/card-item.component.html
- libs/documentation/src/lib/components/result-list/demos/card/result-list-card-component.component.html
- libs/documentation/src/lib/components/result-list/demos/component/result-list-component.component.html
- libs/documentation/src/lib/pages/layout/layout.component.html
- libs/documentation/src/lib/pages/layout/layout.component.ts
- libs/packages/components/src/lib/pagination/pagination.component.html
- libs/packages/components/src/lib/pagination/pagination.component.scss
- libs/packages/components/src/lib/pagination/pagination.component.ts
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
> Configurable search list pagination

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
- libs/documentation/src/lib/components/result-list/demos/card/card-item/card-item.component.html
- libs/documentation/src/lib/components/result-list/demos/card/result-list-card-component.component.html
- libs/documentation/src/lib/components/result-list/demos/component/result-list-component.component.html
- libs/documentation/src/lib/pages/layout/layout.component.html
- libs/documentation/src/lib/pages/layout/layout.component.ts
- libs/packages/components/src/lib/pagination/pagination.component.html
- libs/packages/components/src/lib/pagination/pagination.component.scss
- libs/packages/components/src/lib/pagination/pagination.component.ts
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.spec.ts
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
> Fix multiple getdata calls

- libs/documentation/src/lib/pages/layout/filter.service.ts
- libs/documentation/src/lib/pages/layout/layout.module.ts
- libs/documentation/src/lib/pages/layout/services/autocomplete-sample.data.ts
- libs/documentation/src/lib/pages/layout/services/autocomplete-sample.service.ts
> Add autocomplete to layout example

- libs/documentation/src/lib/shared/component-wrapper/component-wrapper.component.html
> Fix component wrapper for markdown element

- tsconfig.json
> fix tsconfig issue with wrong path

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release to 0.6.25

- angular.json
> updated project order

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
Fixed margins
- [ x] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
> IAE-41461 - top margins

- libs/documentation/src/lib/pages/layout/layout.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.spec.ts
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> Updated filter to avoid multiple API call

- libs/documentation/src/lib/components/download/demos/download/download.component.ts
- libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog-data.model.ts
- libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.html
- libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.ts
> Formly dialog disable submit button configurable

- libs/packages/components/src/lib/pagination/pagination.component.html
> Pagination fixes

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Releasing 0.6.26

- libs/documentation/src/lib/components/table/demos/sort/sort.component.html
- libs/documentation/src/lib/components/table/demos/sort/sort.component.ts
- libs/packages/sam-material-extensions/src/lib/table/table.component.html
- libs/packages/sam-material-extensions/src/lib/table/table.component.spec.ts
- libs/packages/sam-material-extensions/src/lib/table/table.component.ts
Update sort input to accept an array of columns to be sortable. Add sort or sort="true" on the table will still sort on all columns.
> Update sort input to accept an array of columns to be sortable

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Released version to 0.6.27

- libs/documentation/src/lib/components/formly/autocomplete/demos/basic/autocomplete-basic.component.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> Fix for the single select autocomplete

- libs/packages/components/src/lib/public-api.ts
> SdsVideoPlayerComponent is exported

- libs/documentation/src/lib/components/formly/multicheckbox/demos/selectall/multicheckbox-selectall.component.html
- libs/documentation/src/lib/components/formly/multicheckbox/demos/selectall/multicheckbox-selectall.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.spec.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
- package-lock.json
> Reset all url and Multi checkbox demo updates

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release 0.6.28

- libs/packages/components/package.json
> Add ngx-bootstrap-icons as a peer dependency for icons

- libs/packages/sam-material-extensions/src/lib/public-api.ts
> Add button groups to public-api.ts

- CODEOWNERS
> Add new team members

- libs/documentation/src/lib/pages/layout/layout.component.html
- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> Sorting More filter modal contentent

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.ts
- libs/documentation/src/lib/pages/layout/data.service.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.spec.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.module.ts
> Search Results Initial Template added

- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.module.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
> Select All/ deselect All to  more filter modal

- libs/documentation/src/lib/components/video/demos/basic/video-player-sample-data.ts
- libs/packages/components/src/lib/video-player/css/px-video.css
- libs/packages/components/src/lib/video-player/video-player.component.html
- libs/packages/components/src/lib/video-player/video-player.component.spec.ts
- libs/packages/components/src/lib/video-player/video-player.component.ts
you would have to specfy the units now in the configuration file
- [ x] Edge
- [x ] Chrome
> Making video Player Responsive

- libs/documentation/src/lib/components/footer/demos/basic/footer-basic.component.html
- libs/documentation/src/lib/components/footer/demos/basic/footer-basic.component.ts
- libs/documentation/src/lib/components/footer/demos/basic/footer-basic.module.ts
- libs/packages/layouts/src/lib/feature/footer/footer.component.html
- libs/packages/layouts/src/lib/feature/footer/footer.component.spec.ts
- libs/packages/layouts/src/lib/feature/footer/footer.component.ts
- libs/packages/layouts/src/lib/feature/footer/footer.module.ts
- package-lock.json
> 43414 update feedback in footer

- libs/documentation/src/lib/components/icons/demos/basic/icons-basic.component.html
- libs/documentation/src/lib/components/icons/demos/bootstrap/icons-bootstrap.component.html
- libs/documentation/src/lib/components/icons/demos/coloring/icons-coloring.component.html
- libs/documentation/src/lib/components/icons/demos/rotation/icons-rotation.component.html
- libs/documentation/src/lib/components/icons/demos/scaling/icons-scaling.component.html
Added additional details of the inputs and some explanation of the limitations, defaults for the inputs
https://cm-jira.usa.gov/browse/IAE-43164
> IAE-43164 Add details to Icons Documentation

- libs/documentation/src/lib/pages/layout/filter.service.ts
- libs/documentation/src/lib/pages/layout/layout.component.html
- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> SDS More filter sort configuration changes

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release 0.7.1

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> Autocomplete single select mode clear model

- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.html
- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.scss
- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
- libs/documentation/src/lib/components/search/demos/optional/search-optional.component.html
- libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.component.html
- libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.component.ts
- libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.module.ts
- libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.html
- libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.ts
- libs/documentation/src/lib/components/subheader/demos/search/subheader-search.module.ts
- libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.component.html
- libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.component.ts
- libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.module.ts
- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.ts
Search component configurations should be inputed through searchSettings rather than a separate input for each field.
**Note: Potential breaking change**
If MFE is taking advantage of inputClass or parentSelector, input values will need to be updated.
> Update search component to input configurations through searchSettings

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to 0.7.2

- libs/documentation/src/lib/components/formly/multicheckbox/demos/expandable/multicheckbox-expandable.component.html
- libs/documentation/src/lib/components/formly/multicheckbox/demos/expandable/multicheckbox-expandable.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.spec.ts
- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
Passes in tag class and text to more filters multi checkbox
https://cm-jira.usa.gov/browse/IAE-44719
> Allow tag class and text in more filters multi-checkbox

- libs/documentation/src/lib/components/result-list/demos/template/result-list-template.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
> Search results list Noresultstemplate rename 

- libs/packages/layouts/src/lib/feature/system-alert/model/alert.model.ts
- libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.html
- libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.spec.ts
- libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.ts
- libs/packages/layouts/src/lib/feature/system-alert/system-alert.module.ts
> Toggle alert details

- package-lock.json
- package.json
> Revert highlight js downgrade

- libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
Defines a default empty model for autocomplete component
Github issue #478
> Define default model for autocomplete

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> version updated to 10.0.3

- libs/packages/layouts/src/lib/public-api.ts
> updated export form sds-feedback component

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Simply adding the files into the .github directory will create the templates. When users click on New Issue, they should then see the listed questions
> Add bug report and feature request templates

- libs/packages/components/src/lib/external-link/external-link.directive.ts
The Icon is created using CSS class name and also added internal Links array to specify the internal sites
> External link class change

- tools/scripts/pack-and-publish.js
> Update pack-and-publish script

- libs/documentation/src/lib/pages/layout/data.service.ts
- libs/documentation/src/lib/pages/layout/filter.service.ts
Update to filter logic in demo - also check for location filters
> Add filter by location on demo

- libs/documentation/src/lib/components/formly/fileinfo/fileinfo.module.ts
- package-lock.json
> File Info Document title update

- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
> Multi checkbox object values for IE fix

- libs/packages/components/src/lib/search/search.component.html
> Removed placeholder option

- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
> Search-results-initial-template

- apps/sam-design-system-site/src/app/app.component.html
- libs/documentation/src/lib/components/autocomplete/demos/basic/autocomplete-basic.component.html
- libs/documentation/src/lib/components/autocomplete/demos/group/autocomplete-group.component.html
- libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.component.html
- libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.component.ts
- libs/documentation/src/lib/components/autocomplete/demos/selectgroup/autocomplete-selectgroup.component.html
- libs/documentation/src/lib/components/dialog/demos/basic/dialog-basic.component.html
- libs/documentation/src/lib/components/filters/demos/config/fields.ts
- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
- libs/documentation/src/lib/components/search/demos/optional/search-optional.component.ts
- libs/documentation/src/lib/components/shared/examples-page/demo.component.html
- libs/documentation/src/lib/components/video/closing.md
- libs/documentation/src/lib/components/video/demos/basic/video-player-sample-data.ts
- libs/documentation/src/lib/shared/component-wrapper/component-wrapper.component.html
- libs/packages/components/src/lib/accordion/accordion-item-header.component.html
- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.ts
- libs/packages/components/src/lib/toast/toast-single.component.html
- libs/packages/components/src/lib/video-player/video-player.component.html
- libs/packages/components/src/lib/video-player/video-player.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
Accessibility tests done on all pages under 'Components' in our documentation using access assistant chrome extension - https://chrome.google.com/webstore/detail/access-assistant/ojiighldhdmahfdnhfdebnpmlbiemdfm?hl=en
Most of the changes involve adding an aria-label to html, providing option to pass in aria labels, or modifying id in demo so that the id is not unique in DOM.
> Multiple accessibility fixes on documentation site using access assistant

- libs/documentation/src/lib/components/formly-search/demos/basic/search-basic.component.ts
- libs/documentation/src/lib/components/formly-search/demos/optional/search-optional.component.ts
- libs/documentation/src/lib/components/formly-search/demos/submit/search-handle-submit.component.ts
- libs/documentation/src/lib/components/icons/demos/basic/icons-basic.component.html
- libs/documentation/src/lib/components/icons/demos/bootstrap/icons-bootstrap.component.html
- libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.ts
- libs/documentation/src/lib/components/subheader/demos/subpages/subheader-search-sub-pages.component.ts
- libs/documentation/src/lib/components/subheader/demos/workspace/subheader-tier-2-workspace.component.ts
- libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html
- libs/documentation/src/lib/pages/layout/layout.component.html
- libs/packages/components/src/lib/text/text.component.ts
- libs/packages/layouts/src/lib/feature/footer/footer.component.html
- libs/packages/layouts/src/lib/feature/header/header.component.html
- libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.html
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
- libs/packages/sam-formly/src/lib/formly/types/text.ts
More accessibility related changes - Most were documentation side rather than the library itself.
> Access Assistant checks on sam formly and layouts library

- libs/documentation/src/lib/pages/layout/filter.service.ts
- libs/packages/sam-formly/src/lib/formly/formly.config.ts
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/custom-wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.accordian.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
- libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.html
- libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
- libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.ts
Reverts GSA/sam-design-system#525
> Revert "Group wrapper replaced with new accordion"

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.module.ts
- libs/packages/sam-material-extensions/tsconfig.lib.json
> Accordion build fix

- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
> added aria checked back to add tri state for checkbox

- libs/documentation/src/lib/components/formly-search/demos/basic/search-basic.component.ts
- libs/documentation/src/lib/components/formly-search/demos/optional/search-optional.component.ts
- libs/documentation/src/lib/components/formly-search/demos/submit/search-handle-submit.component.ts
- libs/documentation/src/lib/components/search/demos/optional/search-optional.component.ts
> Search-demos updated

- libs/packages/layouts/src/lib/feature/footer/footer.component.html
- libs/packages/layouts/src/lib/feature/header/header.component.html
- libs/packages/layouts/src/lib/feature/sds-feedback/sds-feedback.component.html
Additional 508 fixes for issues that were discovered by entity mfe and not caught in the initial sweep of 508 fixes.
> Resolve outstanding 508 defects reported by entity team

- libs/packages/components/src/lib/external-link/external-link.directive.ts
> Refactoring external link directory

- libs/packages/components/src/lib/accordion/accordion-item.component.spec.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
- libs/packages/components/src/lib/external-link/external-link.directive.spec.ts
- libs/packages/components/src/lib/selection-panel/selection-panel.component.spec.ts
- libs/packages/components/src/lib/toast/toast-single.component.html
- libs/packages/components/src/lib/toast/toast-single.component.ts
- libs/packages/components/src/lib/toast/toast-single.spec.ts
- libs/packages/components/src/lib/toast/toast.module.ts
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.spec.ts
- libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.html
- libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.spec.ts
- libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.spec.ts
- libs/packages/sam-material-extensions/src/lib/button-group/button-group.component.spec.ts
- libs/packages/sam-material-extensions/src/lib/table/table-basic.component.spec.ts
- libs/packages/sam-material-extensions/src/lib/table/table.component.html
- libs/packages/sam-material-extensions/src/lib/table/table.module.ts
Remove focused test on selection panel and resolve issues with unit tests that have been accumulated thus far.
> Resolve failing unit tests

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release 10.0.9

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- package-lock.json
- package.json
> Autocomplete build fix

- libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.html
> Side nav demo updated

- libs/documentation/src/lib/components/filters/demos/group-panel/filters-group-panel.component.html
- libs/documentation/src/lib/components/filters/demos/group-panel/filters-group-panel.component.ts
- libs/documentation/src/lib/components/filters/demos/group-panel/filters-group-panel.module.ts
- libs/documentation/src/lib/components/filters/demos/hideexpression/filters-hideexpression.component.html
- libs/documentation/src/lib/components/filters/demos/optional/filters-optional.component.html
- libs/documentation/src/lib/components/filters/demos/showInactiveFilterValues/filters-showInactiveFilterValues.component.html
- libs/documentation/src/lib/components/filters/filters.module.ts
- libs/documentation/src/lib/components/shared/examples-page/demo.component.html
- libs/documentation/src/lib/components/shared/examples-page/demo.component.ts
- libs/documentation/src/lib/components/shared/examples-page/examples.component.ts
> Filter demo updated 

- libs/documentation/src/lib/components/footer/demos/basic/footer-basic.component.ts
- libs/packages/components/src/lib/external-link/external-link.directive.ts
>  external link to include  FSD link

- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
- libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.ts
- libs/packages/components/src/lib/search-result-list/model/search-results.model.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
> Updated search results to include custom template

- libs/documentation/src/lib/components/shared/examples-page/demo.component.html
- libs/documentation/src/lib/components/shared/examples-page/demo.component.scss
- libs/documentation/src/lib/components/shared/examples-page/demo.component.ts
> Tabs added

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release new version to 10.0.10

- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
> components build fix

- libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.html
- libs/packages/components/src/lib/external-link/external-link.directive.ts
> configurable target for external link

- apps/sam-design-system-site/src/app/app.component.html
- libs/documentation/src/lib/documentation.module.ts
- libs/documentation/src/lib/pages/roadmap/roadmap.component.html
- libs/documentation/src/lib/pages/roadmap/roadmap.component.scss
- libs/documentation/src/lib/pages/roadmap/roadmap.component.ts
- libs/documentation/src/lib/pages/roadmap/roadmap.module.ts
- package-lock.json
- package.json
Adding roadmap page to highlight the features which have been worked on and those still outstanding for the version 1 release of SDS
https://cm-jira.usa.gov/browse/IAEDEV-47071
> IAE-47071: Add Roadmap page

- libs/packages/components/src/lib/selection-panel/selection-panel.component.spec.ts
> Update test for selection panel

- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
> Search results template working

- libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.html
> external-link demo

- libs/packages/layouts/src/lib/feature/footer/footer.component.html
- libs/packages/layouts/src/lib/feature/footer/model/FooterModel.ts
> added Hide icon to the external link

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/layouts/src/lib/feature/footer/footer.component.html
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release 10.0.12

- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.html
- libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.scss
- libs/packages/components/src/lib/search/search.component.ts
- libs/packages/components/src/lib/search/search.module.ts
> configurable suffix search icon added

- .github/ISSUE_TEMPLATE/bug_report.md
Updates issue template to include option for adding JIRA ticket numbers
> Update github issue template

- libs/packages/components/src/lib/video-player/video-player.component.html
- libs/packages/components/src/lib/video-player/video-player.component.ts
- libs/packages/components/src/lib/video-player/video-player.ts
update cross origin option for video players such that it can be changed after view init - https://github.com/GSA/sam-design-system/issues/606
> Add cross origin input option for video player

- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.scss
- package-lock.json
> Search icon alignment chnages

- libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
- package-lock.json
> Reverted disable label state css

- libs/documentation/src/lib/components/result-list/demos/card/card-item.component.html
- libs/documentation/src/lib/components/result-list/demos/card/child-card-item.component.html
- libs/documentation/src/lib/components/result-list/demos/component/child-item.component.html
- libs/documentation/src/lib/components/result-list/demos/component/item.component.html
- package-lock.json
- package.json
Styles to fix alignment have been added to sam-styles, this PR applies those styles to the components used in the documentation to correctly show unique entity ids.
https://cm-jira.usa.gov/browse/IAEDEV-48056
> IAE-48056 Fix alignment of unique entity ids

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> release 10.0.16

- libs/packages/components/src/lib/external-link/external-link.directive.ts
> Aria-label fix for existing value

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Updated version to 10.0.17

- libs/documentation/src/lib/pages/layout/layout.component.html
- libs/documentation/src/lib/pages/layout/layout.component.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
- libs/packages/layouts/package.json
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
- package.json
> Default template for default filter model changes for search-layout

- libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.ts
- libs/documentation/src/lib/components/subheader/demos/subpages/subheader-search-sub-pages.component.ts
- libs/documentation/src/lib/components/subheader/demos/workspace/subheader-tier-2-workspace.component.ts
- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.scss
Search components in our demo are not being responsive to size of containing card.
https://github.com/GSA/sam-design-system/issues/633
> IAE-48852: Update search demo

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Update version 10.0.19

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version update to 10.0.20

- libs/documentation/src/lib/components/accordion/accordion.module.ts
- libs/documentation/src/lib/components/accordion/demos/cardlist/accordion-cardlist.component.html
- libs/documentation/src/lib/components/accordion/demos/cardlist/accordion-cardlist.component.ts
- libs/documentation/src/lib/components/accordion/demos/cardlist/accordion-cardlist.module.ts
Update demo to display accordions inside card list style
> Add demo for accordion list in cards

- README.md
Update readme with instructions on how to link a package to external application for local development
> Add documentation for npm link to readme

- libs/documentation/src/lib/components/toasts/demos/basic/toasts-basic.component.ts
- libs/packages/components/src/lib/toast/toast-single.component.html
- libs/packages/components/src/lib/toast/toast.module.ts
From #671 - We were referencing some classes / icons from font awesome in toast, so converted that to bootstrap
> Git 671 sds toast issue

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Update version to v10.0.21

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> version 10.0.22

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Update version 10.0.23

- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
> more filters' selecting header does not deselect sub items

- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.ts
> More Filters component displaying filter for empty object (GIT-666)

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
> Autocomplete overlap for long names(GIT-676)

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> increment to 10.0.26

- angular.json
- apps/sam-design-system-site/src/app/app.component.html
- apps/sam-design-system-site/src/app/app.component.scss
- apps/sam-design-system-site/src/app/app.component.ts
- apps/sam-design-system-site/src/base-documentation.scss
- apps/sam-design-system-site/src/index.html
- apps/sam-design-system-site/src/sds-styles.scss
- apps/sam-design-system-site/src/uswds-styles.scss
Add a dropdown to allow user to toggle between existing SAM stylesheet and additional stylesheets.
Refactor existing top-level stylesheet to enable needed documentation styles to be imported to specific toggle-able stylesheets.
Update angular.json to create stylesheets for SAM styles and USWDS styles that are separate from other stylings so it can be toggled. (extractCss can be removed when update to Angular11 occurs).
https://cm-jira.usa.gov/browse/IAEDEV-51530
> IAEDEV-51530: Theme switching

- libs/packages/components/package.json
- libs/packages/experimental/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
Bump version to 10.0.28
Bump sam-styles dependency to 0.112
> Version update 10.0.28

- libs/packages/layouts/src/lib/feature/footer/footer.component.html
https://github.com/GSA/sam-design-system/issues/702
> AMP- issue updated aria label for the footer external link

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to 10.0.31

- libs/packages/sam-formly/src/lib/formly/sds-formly.ts
> Abstract sds formly class life cycle hook changes

- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> Date check sonar regex issue

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Update version to 10.0.32

- libs/packages/sam-formly/src/lib/formly/sds-formly.ts
> Change detection removed form sds-fomly

- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
> Persisting  sorting for the layout history tracking

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Updated version 10.0.34

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
- libs/packages/sam-formly/src/lib/formly/readonly/readonly-container.component.html
> Horizontal filters

- libs/documentation/src/lib/components/formly-stepper/demos/advanced/custom-stepper.component.html
- libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.module.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.component.spec.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
- libs/packages/sam-material-extensions/src/lib/table/table.component.spec.ts
Removing the last references to sds-icons in SDS
> Update last references to sds-icon to usa-icon

- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.component.spec.ts
> Update icon module reference for stepper unit test

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Update version to 10.0.36

- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
- package-lock.json
> Enable routing changes

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version Upgrade 10.0.37

- package-lock.json
- package.json
Update sam-styles dependency to 0.116
> Update sam-styles version to 0.116

- libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> inputs with numbers converted to dates issue fix

- libs/documentation/src/lib/components/dialog/demos/alert/dialog-alert.component.ts
- libs/packages/components/src/lib/dialog/dialog-config.ts
- libs/packages/components/src/lib/dialog/dialog-container.component.html
- libs/packages/components/src/lib/dialog/dialog-container.component.ts
- package-lock.json
> Update modal for accepting the success type

- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
Resolve bugs related to calling methods with incorrect number of parameters / referencing non-existent variables
> Prod build bug fixes

- libs/documentation/src/lib/components/formly-checkbox/demos/basic/checkbox-basic.component.ts
- libs/documentation/src/lib/components/formly-radio/demos/basic/radio-basic.component.ts
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
- libs/packages/sam-formly/src/lib/formly/types/checkbox.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
- libs/packages/sam-formly/src/lib/formly/types/radio.html
> Tooltip for the Radio and Checkbox types with information icon

- apps/sam-design-system-site/src/app/app.component.html
> document example name sorted alphabetical

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to 11.0.4

- libs/packages/components/src/lib/tooltip/tooltip.directive.ts
Solution from SO: https://stackoverflow.com/questions/50405930/aot-angular-6-directive-somecomponent-expected-0-arguments-but-got-1-for
> Remove unnecessary event from hostlistener

- libs/packages/components/src/lib/editor/editor.component.ts
> updated fix

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated 11.0.12

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
- package-lock.json
> Autocomplete empty value enter key fix

- libs/packages/components/src/lib/dialog/dialog-animations.ts
- libs/packages/components/src/lib/dialog/dialog-config.ts
- libs/packages/components/src/lib/dialog/dialog-container.component.ts
> Custom width and animation time for Slide Out component

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
Update version for release - Included in this version:
Tree Table
Slide out custom width / animation timing
> Version 11.0.14

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> Hide close icon when then default item value is null

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version upgrade 11.0.15

- libs/documentation/src/lib/components/autocomplete/demos/basic/autocomplete-basic.component.ts
- libs/documentation/src/lib/components/formly-autocomplete/demos/basic/autocomplete-basic.component.html
- libs/documentation/src/lib/components/formly-autocomplete/demos/basic/autocomplete-basic.component.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
- libs/packages/components/src/lib/autocomplete-search/models/SDSAutocompleteConfiguration.ts
- libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts
> Added Optional configurable value to hide close Icon for autocomplete

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> version updated to 11.0.17

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release 11.0.18

- apps/sam-design-system-site/src/app/app.module.ts
- libs/documentation/src/lib/components/selection-panel/demos/basic/basic-selection-panel.component.html
- libs/documentation/src/lib/components/selection-panel/demos/basic/navigation.config.ts
- libs/packages/components/src/lib/selection-panel/navigation-mode/navigation-mode.component.ts
Update selection panel to also include route for navigation purpose. This allows fragment scrolling
Brought up during FWG
> Update selection panel to allow fragment navigation

- libs/packages/components/package.json
- libs/packages/layouts/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Increment version to 11.0.19

- libs/packages/components/src/lib/popover/popover.directive.ts
https://github.com/GSA/sam-design-system/issues/892
> Popover directive space event added

- libs/documentation/src/lib/components/sidenavigation/demos/filter-side-navigation/filter-side-navigation.component.ts
- libs/documentation/src/lib/components/sidenavigation/demos/filter-side-navigation/navigation.config.ts
- libs/documentation/src/lib/components/sidenavigation/demos/links-side-navigation/links-side-navigation.component.html
- libs/documentation/src/lib/components/sidenavigation/demos/links-side-navigation/links-side-navigation.component.ts
- libs/documentation/src/lib/pages/layout/filter.service.ts
- libs/documentation/src/lib/pages/layout/services/autocomplete-sample.service.ts
Resolve demo issue with side navigation component - 
Add root injectable to prevent null injector errors on data services
Add example to pre-select sidenav item
Add example to programmatically select side nav item on click
> Fix issue with sidenav demo

- libs/packages/sam-material-extensions/src/lib/table/table.component.ts
Resolves issues seen with table in demo regarding undefined paginator.
Resolves issue seen with sds table regarding expression change.
> Resolve errors related to undefined paginator and expression change

- libs/documentation/src/lib/components/formly-radio/demos/basic/radio-basic.component.ts
- libs/documentation/src/lib/components/tooltip-popover/demos/basic/popup-basic.component.html
- libs/documentation/src/lib/components/tooltip-popover/demos/basic/popup-basic.module.ts
- libs/packages/components/src/lib/search-result-list/search-result-list.component.html
- libs/packages/components/src/lib/search-result-list/search-result-list.module.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
- libs/packages/sam-formly/src/lib/formly/types/radio.html
> tooltip -- sds-stack replaced and removed option from radio demo

- libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.wrapper.ts
>  small tag removed from wrapper

- libs/packages/components/src/lib/popover/popover.directive.ts
- package-lock.json
> Popover role updated for JAWS checkbox issue 

- libs/packages/components/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to 11.0.22

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
> chip value updated for horizontal filter

- libs/packages/components/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Increment version to 11.0.23

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
https://github.com/GSA/sam-design-system/issues/917
> Autocomplete 508 issue fix

- libs/packages/components/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Version updated to 11.0.25

- libs/documentation/src/lib/components/formly-radio/demos/horizontal/radio-horizontal.component.html
- libs/documentation/src/lib/components/formly-radio/demos/horizontal/radio-horizontal.component.ts
- libs/documentation/src/lib/components/formly-radio/demos/horizontal/radio-horizontal.module.ts
- libs/documentation/src/lib/components/formly-radio/radio.module.ts
- libs/packages/sam-formly/src/lib/formly/types/radio.html
- libs/packages/sam-formly/src/lib/formly/types/radio.scss
- libs/packages/sam-formly/src/lib/formly/types/radio.ts
Added logic to formly radio template to apply a couple of classes to the radio group structure which causes the radio options to be rendered side-by-side rather than vertically stacked. The application of these classes is controlled by the **templateOptions.horizontal** optional value.
IAEDEV-65404
> IAEDEV-65404 Add horizontal templateOption to place options side-by-side

- libs/documentation/src/lib/components/actions/actions.module.ts
- libs/documentation/src/lib/components/actions/demos/action-mode/actions-action-mode.component.html
- libs/documentation/src/lib/components/actions/demos/action-mode/actions-action-mode.component.ts
- libs/documentation/src/lib/components/actions/demos/action-mode/actions-action-mode.module.ts
- libs/documentation/src/lib/components/dialog/demos/alert/dialog-alert.component.ts
- libs/packages/components/src/lib/actions-menu/action-menu.model.ts
- libs/packages/components/src/lib/actions-menu/actions-menu.component.html
- libs/packages/components/src/lib/actions-menu/actions-menu.component.ts
- libs/packages/components/src/lib/menu/menu-item.component.ts
- libs/packages/components/src/lib/menu/menu.component.spec.ts
- libs/packages/components/src/lib/public-api.ts
> Action menu mode changes

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
- package-lock.json
> screen reader value added to the chips

- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
- package-lock.json
> JAW 508 issue for horizontal filter

- libs/packages/components/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Release version updated to11.0.27

- libs/packages/components/src/lib/search/search.component.html
> Search Icon fix

- libs/documentation/src/lib/components/formly-checkbox/checkbox.module.ts
- libs/documentation/src/lib/components/formly-checkbox/demos/template/checkbox-template.component.html
- libs/documentation/src/lib/components/formly-checkbox/demos/template/checkbox-template.component.ts
- libs/documentation/src/lib/components/formly-checkbox/demos/template/checkbox-template.module.ts
- libs/packages/sam-formly/src/lib/formly/types/checkbox.html
- libs/packages/sam-formly/src/lib/formly/types/checkbox.spec.ts
- libs/packages/sam-formly/src/lib/formly/types/checkbox.ts
Added logic to insert dev defined template in place of default when provided.
https://cm-jira.usa.gov/browse/IAEDEV-66008
> IAE-66008: Add template support to checkboxes

- package-lock.json
Issue with package-lock for SDS site, this PR aligns package-lock so that Federalist build passes.
> Fix master fed build

- .prettierrc
- libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.html
- libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.ts
- libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.service.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
> Stepper space for multi checkbox

- libs/packages/sam-material-extensions/src/lib/table/table.component.html
> table icons are changed for expanded row

- libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.service.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
- libs/packages/sam-formly/src/lib/formly/types/radio.html
- libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
> Multi checkbox margin issues

- package-lock.json
- package.json
> sam styles version updated to 0.0.137

- libs/documentation/src/lib/components/table/demos/full/full.component.html
- libs/documentation/src/lib/components/table/demos/full/full.component.ts
- libs/packages/sam-material-extensions/src/lib/table/table.component.html
- libs/packages/sam-material-extensions/src/lib/table/table.component.ts
> Table:  extra margin, position and Icon changes

- libs/documentation/src/lib/components/slide-out/demos/basic/slide-out-template.scss
- libs/documentation/src/lib/components/slide-out/demos/custom-header/custom-header.component.html
- libs/documentation/src/lib/components/slide-out/demos/custom-header/custom-header.component.ts
- libs/documentation/src/lib/components/slide-out/demos/custom-header/custom-header.module.ts
- libs/documentation/src/lib/components/slide-out/demos/template-ref/slide-out-template-ref.component.html
- libs/documentation/src/lib/components/slide-out/demos/template-ref/slide-out-template-ref.component.ts
- libs/documentation/src/lib/components/slide-out/demos/template-ref/slide-out-template-ref.module.ts
- libs/documentation/src/lib/components/slide-out/slide-out.module.ts
> Slide out demo for the custom header

- package-lock.json
- package.json
> styles package updated

- libs/packages/components/src/lib/external-link/external-link.directive.ts
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
> external link wrap and checkbox margin issue

- libs/documentation/src/lib/components/descriptionwrapper/demos/custom-text/descriptionwrapper-custom-text.component.html
- libs/documentation/src/lib/components/descriptionwrapper/demos/custom-text/descriptionwrapper-custom-text.component.ts
- libs/documentation/src/lib/components/descriptionwrapper/demos/custom-text/descriptionwrapper-custom-text.module.ts
- libs/documentation/src/lib/components/descriptionwrapper/descriptionwrapper.module.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts
> Description wrapper updated to use the Inner html

- libs/documentation/src/lib/components/formly-datepicker/datepicker.module.ts
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
> validation changes for date picker

- libs/documentation/src/lib/components/download/demos/formlymodal-curvy/formlymodal-curvy.component.html
- libs/documentation/src/lib/components/download/demos/formlymodal-curvy/formlymodal-curvy.component.ts
- libs/documentation/src/lib/components/download/demos/formlymodal-curvy/formlymodal-curvy.module.ts
- libs/documentation/src/lib/components/download/download.module.ts
- package-lock.json
A formly modal with label and description as link.
> IAE-848 Add link formly modal

- libs/documentation/src/lib/components/labelwrapper/demos/basic/labelwrapper-basic.component.html
- libs/documentation/src/lib/components/labelwrapper/demos/basic/labelwrapper-basic.component.ts
- libs/documentation/src/lib/components/labelwrapper/demos/basic/labelwrapper-basic.module.ts
- libs/packages/components/src/lib/step-arrow/step-arrow.component.html
- libs/packages/components/src/lib/step-arrow/step-arrow.component.scss
- libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
> Label wrapper for template reference

- libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.html
- libs/documentation/src/lib/pages/overview/overview.component.html
> Add usa-class to the links and add unstyled button

- libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.html
- libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.ts
- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.component.spec.ts
- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
Pre populate the model values and validate all forms before loading
https://cm-jira.usa.gov/browse/IAEMOD-1586
> step indicator changes

- .github/workflows/build-and-deploy-storybook.yml
Adds configuration to enable GH pages to deploy storybook to a non-local environment 
https://cm-jira.usa.gov/browse/IAEMOD-2850
https://gsa.github.io/sam-design-system/
> IAEMOD-2850: Add GH Action to deploy storybook

- libs/packages/sam-formly/src/lib/formly/types/input.ts
> input described by added to input type

- libs/documentation/src/lib/components/formly-checkbox/demos/basic/checkbox-basic.component.ts
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
https://github.com/GSA/sam-design-system/issues/1025
> Required Validation added to checkbox radio and multi checkbox

- libs/packages/sam-formly/src/lib/formly/wrappers/form-field.animation.ts
https://github.com/GSA/sam-design-system/issues/1040
> Updating the height to auto to fix the container overflow for the animation wrapper

- libs/packages/sam-formly/src/lib/formly/types/input.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts
https://github.com/GSA/sam-design-system/issues/1037
> description wrapper aria described changes

- libs/documentation/src/lib/components/actions/demos/basic/actions-basic.component.html
- libs/packages/components/src/lib/actions-menu/actions-menu.component.html
- libs/packages/components/src/lib/actions-menu/actions-menu.component.ts
Updated action menu to allow for dev to customize SR text to provide more context for what the action menu will allow the user to do
#1038
> IAEMOD-4032: Update actions menu SR text

- libs/packages/components/src/lib/side-toolbar/side-toolbar.component.ts
Remove toolbar warn console for issue https://github.com/GSA/sam-design-system/issues/1034
> IAE-4037 Remove toolbar warn console

- libs/packages/components/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package.json
> Version updated 12.0.14

- .gitignore
- libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
- package-lock.json
- package.json
> Formly field group Margin updated and  git ignore is updated to not adding cache files

- apps/sam-design-system-site/src/sds-styles.scss
- libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.html
deleted css from sds-styles and added new classes on the advanced filters. now width of search box and the margin issue is fixed.
> Fixed Horizontal filters

- libs/documentation/src/lib/components/tree-table/demos/basic/tree-table-basic.component.html
- libs/packages/components/src/lib/tree-table/tree-table.component.html
Applying fixes for two defects:
The number of rows was incorrectly stated by the screen reader.
The table cells were not announcing the table heading when moving between columns.
Updated table with role=grid
Updated thead and tbody with role=rowgrid
Updated tr with role="row"
Updated component and demo with clearer descriptions for screen readers.
> Tree table 508 fixes

- libs/documentation/src/lib/pages/layout/filter.service.ts
- libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
- package-lock.json
> label wrapper changes

- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.scss
IAEMOD-7343.
removed text-white class from x button and changed it to text-ink class.
Only made changes to search.component.scss and **NOT** sam-styles.
in search.component.scss, added text-ink class and added margin bottom for x button and search icon to align them centraly.
PS. Didnt push using gsa-account because I had already made changes from my personal repo before getting access.
> changed x button color, position of x and search.

- .github/workflows/build-and-deploy-storybook.yml
- angular.json
> Adjust SB build script

- libs/documentation/src/lib/storybook/expires/expires-configurable/expires-configurable.component.html
- libs/documentation/src/lib/storybook/expires/expires-configurable/expires-configurable.component.ts
- libs/documentation/src/lib/storybook/expires/expires-configurable/expires-configurable.module.ts
- libs/documentation/src/lib/storybook/expires/expires-expires/expires-expires.component.html
- libs/documentation/src/lib/storybook/expires/expires-expires/expires-expires.component.ts
- libs/documentation/src/lib/storybook/expires/expires-expires/expires-expires.module.ts
- libs/documentation/src/lib/storybook/expires/expires.stories.ts
- libs/packages/components/src/lib/expires/expires.directive.ts
Add Expires Demos to Storybook
IAEMOD-8612
> IAEMOD-8612: Add Expires Demos to Storybook

- libs/documentation/src/lib/storybook/date-pipe/date-pipe-current-day/date-pipe-current-day.component.html
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-current-day/date-pipe-current-day.component.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-current-day/date-pipe-current-day.module.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-current-year/date-pipe-current-year.component.html
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-current-year/date-pipe-current-year.component.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-current-year/date-pipe-current-year.module.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-non-current-year/date-pipe-non-current-year.component.html
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-non-current-year/date-pipe-non-current-year.component.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-non-current-year/date-pipe-non-current-year.module.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe.stories.ts
Add Date-pipe demos to Storybook
IAEMOD-8611
> Add Date-pipe demos to Storybook

- .github/workflows/build-and-deploy-storybook.yml
- package.json
Update branch which GH action build is triggered off of.
IAEMOD-8892
> Update gh action branch

- libs/documentation/src/lib/components/collapse/collapse.module.ts
- libs/documentation/src/lib/components/collapse/demos/collapse-link-to-sb/collapse-link-to-sb.component.html
- libs/documentation/src/lib/components/collapse/demos/collapse-link-to-sb/collapse-link-to-sb.component.ts
- libs/documentation/src/lib/components/collapse/demos/collapse-link-to-sb/collapse-link-to-sb.module.ts
- libs/documentation/src/lib/storybook/collapse/collapse-basic/collapse-basic.component.html
- libs/documentation/src/lib/storybook/collapse/collapse-basic/collapse-basic.component.ts
- libs/documentation/src/lib/storybook/collapse/collapse-basic/collapse-basic.module.ts
- libs/documentation/src/lib/storybook/collapse/collapse-introduction/collapse-introduction.component.html
- libs/documentation/src/lib/storybook/collapse/collapse-introduction/collapse-introduction.component.ts
- libs/documentation/src/lib/storybook/collapse/collapse-introduction/collapse-introduction.module.ts
- libs/documentation/src/lib/storybook/collapse/collapse.stories.ts
Added basic demo and introduction for collapse. Did not include a configurable demo as there is only one input for this directive, the element which the directive is applied to.
Added link from old SDS demos to new SB demos
IAEMOD-9184
> IAEMOD-9184: Add Collapse Demos to SB

- libs/documentation/src/lib/storybook/autocomplete/autocomplete-introduction/autocomplete-introduction.component.html
- libs/documentation/src/lib/storybook/autocomplete/autocomplete-introduction/autocomplete-introduction.component.ts
- libs/documentation/src/lib/storybook/autocomplete/autocomplete-introduction/autocomplete-introduction.module.ts
- libs/documentation/src/lib/storybook/autocomplete/autocomplete.stories.ts
- libs/documentation/src/lib/storybook/button-group/button-group-introduction/button-group-introduction.component.html
- libs/documentation/src/lib/storybook/button-group/button-group-introduction/button-group-introduction.component.ts
- libs/documentation/src/lib/storybook/button-group/button-group-introduction/button-group-introduction.module.ts
- libs/documentation/src/lib/storybook/button-group/button-group.stories.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-introduction/date-pipe-introduction.component.html
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-introduction/date-pipe-introduction.component.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe-introduction/date-pipe-introduction.module.ts
- libs/documentation/src/lib/storybook/date-pipe/date-pipe.stories.ts
- libs/documentation/src/lib/storybook/expires/expires-introduction/expires-introduction.component.html
- libs/documentation/src/lib/storybook/expires/expires-introduction/expires-introduction.component.ts
- libs/documentation/src/lib/storybook/expires/expires-introduction/expires-introduction.module.ts
- libs/documentation/src/lib/storybook/expires/expires.stories.ts
- libs/documentation/src/lib/storybook/external-link/external-link-introduction/external-link-introduction.component.html
- libs/documentation/src/lib/storybook/external-link/external-link-introduction/external-link-introduction.component.ts
- libs/documentation/src/lib/storybook/external-link/external-link-introduction/external-link-introduction.module.ts
- libs/documentation/src/lib/storybook/external-link/external-link.stories.ts
- libs/documentation/src/lib/storybook/popover/popover-introduction/popover-introduction.component.html
- libs/documentation/src/lib/storybook/popover/popover-introduction/popover-introduction.component.ts
- libs/documentation/src/lib/storybook/popover/popover-introduction/popover-introduction.module.ts
- libs/documentation/src/lib/storybook/popover/popover.stories.ts
- libs/documentation/src/lib/storybook/search/search-introduction/search-introduction.component.html
- libs/documentation/src/lib/storybook/search/search-introduction/search-introduction.component.ts
- libs/documentation/src/lib/storybook/search/search-introduction/search-introduction.module.ts
- libs/documentation/src/lib/storybook/search/search.stories.ts
Added introduction story to component stories which has previously been migrated to storybook. These introductions are not the final version and are merely placeholders for a future story which provide further, and more specific details for each component.
IAEMOD-9188
> IAEMOD-9188: Add introduction to previously migrates SB demos

- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
Skip the multiple change step when it's the linear mode, this functionality was added for pre-validating the step on load in a regular mode.
Here is the issue
https://github.com/GSA/sam-design-system/issues/1041
> Stepper Skipping the step change for initial validation in linear mode

- libs/packages/sam-formly/src/lib/formly/formly.module.ts
This PR for updating the validation date formatting.
https://cm-jira.usa.gov/browse/IAEMOD-9775
> date formate changes mmm dd, yyyy

- libs/documentation/src/lib/storybook/actions/actions.stories.ts
Fixing bug in actions configurable where actions input is not tied to the component.
IAEMOD-9183
> IAEMOD-9183: Fix actions configurable - actions input

- libs/documentation/src/lib/components/pagination/demos/pagination-link-to-sb/pagination-link-to-sb.component.html
- libs/documentation/src/lib/components/pagination/demos/pagination-link-to-sb/pagination-link-to-sb.component.ts
- libs/documentation/src/lib/components/pagination/demos/pagination-link-to-sb/pagination-link-to-sb.module.ts
- libs/documentation/src/lib/components/pagination/pagination.module.ts
- libs/documentation/src/lib/storybook/pagination/pagination-configurable/pagination-configurable.component.html
- libs/documentation/src/lib/storybook/pagination/pagination-configurable/pagination-configurable.component.ts
- libs/documentation/src/lib/storybook/pagination/pagination-configurable/pagination-configurable.module.ts
- libs/documentation/src/lib/storybook/pagination/pagination-display-mode/pagination-display-mode.component.html
- libs/documentation/src/lib/storybook/pagination/pagination-display-mode/pagination-display-mode.component.ts
- libs/documentation/src/lib/storybook/pagination/pagination-display-mode/pagination-display-mode.module.ts
- libs/documentation/src/lib/storybook/pagination/pagination-introduction/pagination-introduction.component.html
- libs/documentation/src/lib/storybook/pagination/pagination-introduction/pagination-introduction.component.ts
- libs/documentation/src/lib/storybook/pagination/pagination-introduction/pagination-introduction.module.ts
- libs/documentation/src/lib/storybook/pagination/pagination-page/pagination-page.component.html
- libs/documentation/src/lib/storybook/pagination/pagination-page/pagination-page.component.ts
- libs/documentation/src/lib/storybook/pagination/pagination-page/pagination-page.module.ts
- libs/documentation/src/lib/storybook/pagination/pagination-total-items/pagination-total-items.component.html
- libs/documentation/src/lib/storybook/pagination/pagination-total-items/pagination-total-items.component.ts
- libs/documentation/src/lib/storybook/pagination/pagination-total-items/pagination-total-items.module.ts
- libs/documentation/src/lib/storybook/pagination/pagination.stories.ts
Add demos for pagination in storybook
Add link from old documentation to new storybook demos
IAEMOD-9758
> IAEMOD-9758: Add pagination demos for SB

- libs/documentation/src/lib/components/formly-multicheckbox/demos/basic/multicheckbox-basic.component.ts
- libs/packages/sam-formly/src/lib/formly/formly.module.ts
- libs/packages/sam-formly/src/lib/formly/formly.validators.ts
- libs/packages/sam-formly/src/lib/public-api.ts
- package-lock.json
- package.json
This is the custom validation method for the multi-checkbox required validation.
> Multicheckbox validation

- libs/documentation/src/lib/components/result-list/demos/result-list-link-to-sb/result-list-link-to-sb.component.html
- libs/documentation/src/lib/components/result-list/demos/result-list-link-to-sb/result-list-link-to-sb.component.ts
- libs/documentation/src/lib/components/result-list/demos/result-list-link-to-sb/result-list-link-to-sb.module.ts
- libs/documentation/src/lib/components/result-list/result-list.module.ts
- libs/documentation/src/lib/storybook/result-list/result-list-basic/result-list-basic.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-basic/result-list-basic.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-basic/result-list-basic.module.ts
- libs/documentation/src/lib/storybook/result-list/result-list-configurable/result-list-configurable.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-configurable/result-list-configurable.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-configurable/result-list-configurable.module.ts
- libs/documentation/src/lib/storybook/result-list/result-list-custom-component/list-component/list-component.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-custom-component/list-component/list-component.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-custom-component/result-list-custom-component.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-custom-component/result-list-custom-component.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-custom-component/result-list-custom-component.module.ts
- libs/documentation/src/lib/storybook/result-list/result-list-custom-template/result-list-custom-template.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-custom-template/result-list-custom-template.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-custom-template/result-list-custom-template.module.ts
- libs/documentation/src/lib/storybook/result-list/result-list-introduction/result-list-introduction.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-introduction/result-list-introduction.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-introduction/result-list-introduction.module.ts
- libs/documentation/src/lib/storybook/result-list/result-list-messages/result-list-messages.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-messages/result-list-messages.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-messages/result-list-messages.module.ts
- libs/documentation/src/lib/storybook/result-list/result-list.stories.ts
Add demos for result list to storybook
Add link from SDS docs to Storybook
IAEMOD-9760
> IAEMOD-9760: Add Result List to Storybook

- libs/documentation/src/lib/storybook/result-list/result-list-custom-template/result-list-custom-template.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-custom-template/result-list-custom-template.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-messages/optional-classes.ts
- libs/documentation/src/lib/storybook/result-list/result-list-messages/result-list-messages.component.html
- libs/documentation/src/lib/storybook/result-list/result-list-messages/result-list-messages.component.ts
- libs/documentation/src/lib/storybook/result-list/result-list-messages/result-list-messages.module.ts
Change custom template demo to not reflect currently used pattern to hopefully avoid someone thinking that the template is an approved version and pasting it into production code.
Update messages demo to allow for switching between known patterns, it is different from basic demo on SDS in that the model switching is all done in code improving readability.
IAEMOD-9760
Updated template demo:
Updated messages demo:
> IAEMOD-9760: Updates based on demo

- libs/documentation/src/sandbox/sandbox-utils.ts
Update createCodePreviewTabData to allow for custom tab title
Update createCodePreviewTabData to allow for custom tab title
> Update createCodePreviewTabData to allow for custom tab title

- .prettierignore
- libs/documentation/src/lib/components/toasts/demos/toasts-link-to-sb/toasts-link-to-sb.component.html
- libs/documentation/src/lib/components/toasts/demos/toasts-link-to-sb/toasts-link-to-sb.component.ts
- libs/documentation/src/lib/components/toasts/demos/toasts-link-to-sb/toasts-link-to-sb.module.ts
- libs/documentation/src/lib/components/toasts/toasts.module.ts
- libs/documentation/src/lib/storybook/toasts/toasts-configurable/toasts-configurable.component.html
- libs/documentation/src/lib/storybook/toasts/toasts-configurable/toasts-configurable.component.ts
- libs/documentation/src/lib/storybook/toasts/toasts-configurable/toasts-configurable.module.ts
- libs/documentation/src/lib/storybook/toasts/toasts-introduction/toasts-introduction.component.html
- libs/documentation/src/lib/storybook/toasts/toasts-introduction/toasts-introduction.component.ts
- libs/documentation/src/lib/storybook/toasts/toasts-introduction/toasts-introduction.module.ts
- libs/documentation/src/lib/storybook/toasts/toasts-message/toasts-message.component.html
- libs/documentation/src/lib/storybook/toasts/toasts-message/toasts-message.component.ts
- libs/documentation/src/lib/storybook/toasts/toasts-message/toasts-message.module.ts
- libs/documentation/src/lib/storybook/toasts/toasts-prevent-duplicates/toasts-prevent-duplicates.component.html
- libs/documentation/src/lib/storybook/toasts/toasts-prevent-duplicates/toasts-prevent-duplicates.component.ts
- libs/documentation/src/lib/storybook/toasts/toasts-prevent-duplicates/toasts-prevent-duplicates.module.ts
- libs/documentation/src/lib/storybook/toasts/toasts-timeout/toasts-timeout.component.html
- libs/documentation/src/lib/storybook/toasts/toasts-timeout/toasts-timeout.component.ts
- libs/documentation/src/lib/storybook/toasts/toasts-timeout/toasts-timeout.module.ts
- libs/documentation/src/lib/storybook/toasts/toasts-type/toasts-type.component.html
- libs/documentation/src/lib/storybook/toasts/toasts-type/toasts-type.component.ts
- libs/documentation/src/lib/storybook/toasts/toasts-type/toasts-type.module.ts
- libs/documentation/src/lib/storybook/toasts/toasts.stories.ts
- libs/packages/components/src/lib/toast/toast-single.component.html
- libs/packages/components/src/lib/toast/toast-single.component.ts
Add demos for toast to storybook.
Resolves #1133 
#1137 
#1133
> Add Toast Demos to Storybook

- libs/documentation/src/lib/storybook/actions/actions-label/actions-label.component.html
- libs/packages/components/src/lib/actions-menu/actions-menu.component.html
- libs/packages/components/src/lib/actions-menu/actions-menu.component.ts
This is the feature request to disable the action menu.
https://github.com/GSA/sam-design-system/issues/1135
> Action menu disable

- libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.html
Padding added for the sds-modal content
Git issue : https://github.com/GSA/sam-design-system/issues/1147
> Padding added for download model content

- libs/packages/sam-formly/src/lib/formly/formly.validators.ts
This PR is to update the datepicker validation to accept date on or before/after date.
Git issue: https://github.com/GSA/sam-design-system/issues/1116
> Date validator : Updated to accept min and max on or before/ after date

- libs/documentation/src/lib/components/selection-panel/demos/selection-panel-link-to-sb/selection-panel-link-to-sb.component.html
- libs/documentation/src/lib/components/selection-panel/demos/selection-panel-link-to-sb/selection-panel-link-to-sb.component.ts
- libs/documentation/src/lib/components/selection-panel/demos/selection-panel-link-to-sb/selection-panel-link-to-sb.module.ts
- libs/documentation/src/lib/components/selection-panel/selection-panel.module.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-children/selection-panel-children.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-children/selection-panel-children.component.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-children/selection-panel-children.config.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-children/selection-panel-children.module.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-configurable/selection-panel-configurable.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-configurable/selection-panel-configurable.component.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-configurable/selection-panel-configurable.module.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-introduction/selection-panel-introduction.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-introduction/selection-panel-introduction.component.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-introduction/selection-panel-introduction.module.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-mode/selection-panel-mode.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-mode/selection-panel-mode.component.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-mode/selection-panel-mode.config.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-mode/selection-panel-mode.module.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-selected/selection-panel-selected.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-selected/selection-panel-selected.component.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-selected/selection-panel-selected.config.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-selected/selection-panel-selected.module.ts
- libs/documentation/src/lib/storybook/selection-panel/selection-panel.stories.ts
Add Selection Panel demos to Storybook
#1149
> Add Selection Panel demos to Storybook

- libs/documentation/src/lib/storybook/selection-panel/selection-panel-children/selection-panel-children.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-configurable/selection-panel-configurable.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-mode/selection-panel-mode.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-selected/selection-panel-selected.component.html
- libs/documentation/src/lib/storybook/selection-panel/selection-panel-selected/selection-panel-selected.config.ts
Demo feedback, adjust the width of selection panels in demos
> Adjust width of selection-panel demos

- CODEOWNERS
> Clean up codeowners

- libs/packages/sam-formly/src/lib/formly/types/checkbox.html
- libs/packages/sam-formly/src/lib/formly/types/radio.html
- libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
This PR is for fixing the tooltip margin issues
https://github.com/GSA/sam-design-system/issues/1164
> Tooltip padding

- libs/documentation/src/lib/components/formly-tabs/demos/formly-tabs-link-to-sb/formly-tabs-link-to-sb.component.html
- libs/documentation/src/lib/components/formly-tabs/demos/formly-tabs-link-to-sb/formly-tabs-link-to-sb.component.ts
- libs/documentation/src/lib/components/formly-tabs/demos/formly-tabs-link-to-sb/formly-tabs-link-to-sb.module.ts
- libs/documentation/src/lib/components/formly-tabs/formly-tabs.module.ts
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-basic/formly-tabs-basic.component.html
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-basic/formly-tabs-basic.component.ts
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-basic/formly-tabs-basic.module.ts
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-intercept/formly-tabs-intercept.component.html
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-intercept/formly-tabs-intercept.component.ts
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-intercept/formly-tabs-intercept.module.ts
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-introduction/formly-tabs-introduction.component.html
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-introduction/formly-tabs-introduction.component.ts
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs-introduction/formly-tabs-introduction.module.ts
- libs/documentation/src/lib/storybook/formly/formly-tabs/formly-tabs.stories.ts
> Add tabs demo to storybook

- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-basic/formly-file-info-basic.component.html
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-basic/formly-file-info-basic.component.ts
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-basic/formly-file-info-basic.module.ts
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-introduction/formly-file-info-introduction.component.html
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-introduction/formly-file-info-introduction.component.ts
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-introduction/formly-file-info-introduction.module.ts
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-options/formly-file-info-options.component.html
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-options/formly-file-info-options.component.ts
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info-options/formly-file-info-options.module.ts
- libs/documentation/src/lib/storybook/formly/formly-file-info/formly-file-info.stories.ts
> sb formly file info

- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-basic/formly-checkbox-basic.component.html
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-basic/formly-checkbox-basic.component.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-basic/formly-checkbox-basic.module.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-description/formly-checkbox-description.component.html
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-description/formly-checkbox-description.component.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-description/formly-checkbox-description.module.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-introduction/formly-checkbox-introduction.component.html
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-introduction/formly-checkbox-introduction.component.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-introduction/formly-checkbox-introduction.module.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-label/formly-checkbox-label.component.html
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-label/formly-checkbox-label.component.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-label/formly-checkbox-label.module.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-nested/formly-checkbox-nested.component.html
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-nested/formly-checkbox-nested.component.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-nested/formly-checkbox-nested.module.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-required/formly-checkbox-required.component.html
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-required/formly-checkbox-required.component.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-required/formly-checkbox-required.module.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-template/formly-checkbox-template.component.html
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-template/formly-checkbox-template.component.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-template/formly-checkbox-template.module.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-tooltip/formly-checkbox-tooltip.component.html
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-tooltip/formly-checkbox-tooltip.component.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox-tooltip/formly-checkbox-tooltip.module.ts
- libs/documentation/src/lib/storybook/formly/formly-checkbox/formly-checkbox.stories.ts
> sb formly checkbox

- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-configurable/formly-select-configurable.component.html
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-configurable/formly-select-configurable.component.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-configurable/formly-select-configurable.module.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-description/formly-select-description.component.html
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-description/formly-select-description.component.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-description/formly-select-description.module.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-introduction/formly-select-introduction.component.html
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-introduction/formly-select-introduction.component.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-introduction/formly-select-introduction.module.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-label/formly-select-label.component.html
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-label/formly-select-label.component.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-label/formly-select-label.module.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-options/formly-select-options.component.html
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-options/formly-select-options.component.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-options/formly-select-options.module.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-required/formly-select-required.component.html
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-required/formly-select-required.component.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select-required/formly-select-required.module.ts
- libs/documentation/src/lib/storybook/formly/formly-select/formly-select.stories.ts
> sb formly select

- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-advanced/formly-radio-advanced.component.html
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-advanced/formly-radio-advanced.component.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-advanced/formly-radio-advanced.module.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-basic/formly-radio-basic.component.html
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-basic/formly-radio-basic.component.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-basic/formly-radio-basic.module.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-group/formly-radio-group.component.html
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-group/formly-radio-group.component.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-group/formly-radio-group.module.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-horizontal/formly-radio-horizontal.component.html
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-horizontal/formly-radio-horizontal.component.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-horizontal/formly-radio-horizontal.module.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-introduction/formly-radio-introduction.component.html
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-introduction/formly-radio-introduction.component.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-introduction/formly-radio-introduction.module.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-template/formly-radio-template.component.html
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-template/formly-radio-template.component.scss
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-template/formly-radio-template.component.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-template/formly-radio-template.module.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio.stories.ts
> Sb formly radio

- libs/packages/sam-formly/src/lib/formly/types/checkbox.html
- libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
- libs/packages/sam-formly/src/lib/formly/types/radio.html
- libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
https://github.com/GSA/sam-design-system/issues/1190
> Tooltip icon changes

- libs/documentation/src/lib/storybook/formly/formly-multi-checkbox/formly-multi-checkbox-group/formly-multi-checkbox-group.component.html
- libs/documentation/src/lib/storybook/formly/formly-multi-checkbox/formly-multi-checkbox-group/formly-multi-checkbox-group.component.ts
- libs/documentation/src/lib/storybook/formly/formly-multi-checkbox/formly-multi-checkbox-nested/formly-multi-checkbox-nested.component.ts
removed broken tooltip and added pre tag
> remove tooltip and add pre tag

- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-advanced/formly-search-advanced.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-basic/formly-search-basic.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-big/formly-search-big.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-dropdown/formly-search-dropdown.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-handling-submit/formly-search-handling-submit.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-introduction/formly-search-introduction.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-label/formly-search-label.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-label/formly-search-label.component.ts
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-optional/formly-search-optional.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-placeholder/formly-search-placeholder.component.html
> add pre to model json

- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-basic/formly-radio-basic.component.html
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-group/formly-radio-group.component.html
> added pre tag

- libs/documentation/src/lib/storybook/utilities/icons/icons.stories.ts
> fix sb icons stackblitz

- libs/documentation/src/lib/components/formly-file-input/demos/file-input-template/file-input-template.component.ts
- libs/documentation/src/lib/storybook/formly/formly-file-input/formly-file-input-custom/formly-file-input-custom.component.html
- libs/documentation/src/lib/storybook/formly/formly-file-input/formly-file-input-custom/formly-file-input-custom.component.ts
- libs/documentation/src/lib/storybook/formly/formly-file-input/formly-file-input-custom/formly-file-input-custom.module.ts
Fix issue where onModelChange function gave a console error because the right parameter weren’t passed
> Sds formly fileinput

- libs/documentation/src/lib/storybook/tree-table/tree-table-basic/tree-table-basic.component.html
- libs/documentation/src/lib/storybook/tree-table/tree-table-configurable/tree-table-configurable.component.html
- libs/documentation/src/lib/storybook/tree-table/tree-table-programmatic-control/tree-table-programmatic-control.component.html
Add href to allow for tabbing to all rows including those without children
Addresses #1123
> 1123: Update demo to allow for tabbing

- libs/documentation/src/lib/storybook/dialog/dialog-alert-type/dialog-template.component.html
- libs/documentation/src/lib/storybook/dialog/dialog-configurable/dialog-configurable-template.component.html
- libs/documentation/src/lib/storybook/dialog/dialog-configurable/dialog-configurable.module.ts
- libs/documentation/src/lib/storybook/dialog/dialog-data-return/dialog-data-return.module.ts
- libs/documentation/src/lib/storybook/dialog/dialog-data-return/dialog-template.component.html
- libs/documentation/src/lib/storybook/dialog/dialog-data-return/dialog-template.component.scss
- libs/documentation/src/lib/storybook/dialog/dialog-data-return/dialog-template.component.ts
- libs/documentation/src/lib/storybook/dialog/dialog-nested/dialog-nested.component.html
- libs/documentation/src/lib/storybook/dialog/dialog-nested/dialog-template.component.html
- libs/documentation/src/lib/storybook/dialog/dialog-nested/second-nested-dialog.component.html
- libs/documentation/src/lib/storybook/dialog/dialog-policy/dialog-policy.component.html
- libs/documentation/src/lib/storybook/dialog/dialog-policy/dialog-policy.component.ts
- libs/documentation/src/lib/storybook/dialog/dialog-policy/dialog-policy.module.ts
- libs/documentation/src/lib/storybook/dialog/dialog-policy/official-template.component.html
- libs/documentation/src/lib/storybook/dialog/dialog-policy/official-template.component.ts
- libs/documentation/src/lib/storybook/dialog/dialog-width/dialog-template.component.html
- libs/documentation/src/lib/storybook/dialog/dialog.stories.ts
Update storybook demos to be more than just text in a dialog. Utilize dialog directives to mark sections as headers, content, and actions
#1199
> Update Dialog Storybook Demos

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
- libs/packages/components/src/lib/selected-result/selected-result.component.html
This PR is to resolve the below issues related to autocomplete, added feature update the model value on blur when autocomplete is single mode and Free text enabled or tag mode enabled
https://github.com/GSA/sam-design-system/issues/1271
https://github.com/GSA/sam-design-system/issues/1182
https://github.com/GSA/sam-design-system/issues/1182
> Autocomplete on blur for tag and free text and extra space for the chip text 

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
- libs/packages/components/src/lib/selected-result/selected-result.component.html
Updated selected item value in autocomplete, when you type and select anything from keyboard keys the item was not selecting.
https://github.com/GSA/sam-design-system/issues/1153
> Autocomplete Keyboard selection not working

- libs/packages/sam-material-extensions/src/lib/table/table.component.html
https://github.com/GSA/sam-design-system/issues/1129
The purpose of the PR to resolve the above issue for the expansion table icon having extra space.
Margin left added to the expansion column as it was having extra space
> Table: Margin left added to the expansion column as it was having extra space

- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-advanced/formly-search-advanced.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-basic/formly-search-basic.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-big/formly-search-big.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-dropdown/formly-search-dropdown.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-handling-submit/formly-search-handling-submit.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-label/formly-search-label.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-optional/formly-search-optional.component.html
- libs/documentation/src/lib/storybook/formly/formly-search/formly-search-placeholder/formly-search-placeholder.component.html
fixed pre tag for storybook formly search
This change removes a leading tab character which caused the horizontal alignment of the opening and closing curly braces to be off.
removed the leading tab to fix the alignment
> fixed pre tag alignment

- libs/packages/components/src/lib/actions-menu/actions-menu.component.html
> Action menu disable button size and color

- package.json
> sam style package version updated

- libs/packages/components/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
Increment version to 15.0.3 for release
> Increment to v15.0.3

- libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
- libs/packages/sam-formly/src/lib/formly/types/daterangepicker.ts
Fixed the calander icon size in date picker and added padding left. and added calender icon to datepicker range
> Date picker icon

- libs/packages/sam-formly/src/lib/formly/formly.module.ts
- libs/packages/sam-formly/src/lib/formly/types/input.ts
> Clear icon added to the input component

- .github/workflows/build-and-deploy-storybook.yml
Update node version. My guess at the reason this error is occurring is that the GH pages script is currently running in nodev14 which conflicts with lockfile version, as shown in this screenshot:
To try and be helpful, npm re-works the lockfile, which must introduce a version that is causing an error. By updating the node version, we:
1) Keep the node version consistant with what is running on dev machines
2) Remove the need to npm to try and help by re-working the lockfile
Additionally, I've tested this fix on my machine with the following proceedure: 
1) Start with nodev16 and run `npm run build-storybook-ng` - no error
2) Change to nodev14 and run `npm run build-storybook-ng` - Same error as in GH pages
3) Change back to nodev16 and run `npm run build-storybook-ng` - no error
Resolves …
> 1340: Update node version to resolve SB build error

- libs/documentation/src/lib/storybook/formly/formly-dialog/formly-dialog-download/formly-dialog-download.component.ts
- libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.html
- libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.ts
https://github.com/GSA/sam-design-system/issues/1358
> Disable submit button on Modal change

- .github/workflows/build-and-deploy-storybook.yml
This PR fixes GH Pages build by having NG CLI used rather than expecting it to be available when called by npm run script.
Latest build can be found at this link:
https://gsa.github.io/sam-design-system/
With NG 16/Storybook 7 updates the GH Pages build broke.
Build passing after updates:
> Fix GH Pages deployment

- libs/documentation/src/lib/storybook/formly/formly-multi-checkbox/formly-multi-checkbox-nested/formly-multi-checkbox-nested.component.ts
> checkbox label changes for storybook demo

- libs/documentation/src/lib/components/formly-file-input/demos/basic-file-input/basic-file-input.component.ts
- libs/documentation/src/lib/storybook/formly/formly-file-input/formly-file-input-basic/formly-file-input-basic.component.ts
> Storybook file input demo fix

- package-lock.json
- package.json
Fixed last issue with formyl demos not loading in stackblitz
Formly demos have been broken for a while in stackblitz, this PR addresses the last issue to make it work again
Before:
After:
> Update package to allow formly demos to work in v16

- .github/workflows/build-and-deploy-storybook.yml
- .storybook/main.cjs
- libs/documentation/src/lib/storybook/formly/formly-multi-checkbox/formly-multi-checkbox-nested/formly-multi-checkbox-nested.component.html
- package-lock.json
- package.json
fix path issue for /uswds/img
fixed paths for Github pages, now it shows the uswds imgs
> Gh pages checkbox

- libs/documentation/src/lib/storybook/formly/formly-input/formly-input-affix/formly-input-affix.component.ts
- libs/packages/sam-formly/src/lib/formly/types/input.ts
- libs/packages/sam-formly/src/lib/formly/types/radio.html
This PR is to add the callback function for the suffix and prefix.
Changing the x Icon position to the end.
Replacing the '-' to '_' of the description for the radio button
> Input enhancement adding callback function for the prefix/suffix and description for the radio button

- libs/packages/sam-formly/src/lib/formly/types/radio.html
> Revert the description changes for the Radio button

- .github/workflows/build-and-deploy-storybook.yml
- .github/workflows/pr-workflow.yml
- .storybook/main.cjs
Adding support for pr-branches
> Adding support for pr-branches

- libs/packages/sam-formly/src/lib/formly/types/radio.html
The radio button aria-described by should have the correct ID for the radio group description.
https://github.com/GSA/sam-design-system/issues/1387
> Radio description ID for aria describe by property 

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
close the results for tag mode
- [ x] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
> fixed tag mode dropdown

- libs/packages/components/src/lib/search/search.component.html
- libs/packages/components/src/lib/search/search.component.ts
This PR is to add  focus to the x (clear icon). Hiding the default x icon and added a new USA Icon
> Search focus change and Icon replace

- libs/packages/components/src/lib/search/search.component.ts
- libs/packages/sam-formly/src/lib/formly/types/radio.html
- libs/packages/sam-formly/src/lib/formly/types/radio.ts
This PR is for refactoring the Radio button custom option class name
> Radio button to accept the custom option class name changes

- libs/packages/components/src/lib/search/search.component.html
- libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.html
- libs/packages/sam-formly/src/lib/formly/types/radio.html
> Formly dialog Disable submit button functionality changes

- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-group/formly-radio-group.component.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-horizontal/formly-radio-horizontal.component.ts
- libs/documentation/src/lib/storybook/formly/formly-radio/formly-radio-template/formly-radio-template.component.ts
This PR is for fixing the demo for the Template, group,Horizontal examples
> Radio button demo breaking with label

- libs/documentation/src/lib/storybook/formly/formly-autocomplete/formly-autocomplete-id/formly-autocomplete-id.component.ts
Add message based on demo feedback
> Add 508 warning to demo

- libs/documentation/src/lib/components/sidenavigation/demos/filter-side-navigation/filter-side-navigation.component.html
- libs/documentation/src/lib/components/sidenavigation/sidenavigation.module.ts
- libs/documentation/src/lib/storybook/side-navigation/side-navigation-filters/side-navigation-filters.component.html
- libs/packages/components/src/lib/side-toolbar/side-toolbar.component.html
- libs/packages/components/src/lib/side-toolbar/side-toolbar.component.ts
This PR is for sidenav enhancement to allow Icon in the button and full width for the responsive size
https://github.com/GSA/sam-design-system/issues/1347
> Side nav enhancements

- .github/workflows/build-and-deploy-storybook.yml
- .github/workflows/build.yml
- .github/workflows/pr-workflow.yml
Reduce the amount of duplicated workflow I've moved the actual build steps into its own workflow that is called by both the master deployment and PR deployment workflows.
Reduce the amount of duplicated workflow I've moved the actual build steps into its own workflow that is called by both the master deployment and PR deployment workflows.
> Update workflows to use the same build workflow

- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area-configurable/formly-text-area-configurable.component.ts
- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area-maxlength/formly-text-area-maxlength.component.ts
- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area-width/formly-text-area-width.component.html
- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area-width/formly-text-area-width.component.ts
- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area-width/formly-text-area-width.module.ts
- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area.stories.ts
- libs/packages/sam-formly/src/lib/formly/types/textarea.spec.ts
- libs/packages/sam-formly/src/lib/formly/types/textarea.ts
- package.json
> Text area width

- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area-maxlength/formly-text-area-maxlength.component.ts
- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area-width/formly-text-area-width.component.ts
- libs/packages/sam-formly/src/lib/formly/types/textarea.spec.ts
- libs/packages/sam-formly/src/lib/formly/types/textarea.ts
> remove ng class

- libs/documentation/src/lib/storybook/formly/formly-filter/formly-filter-horizontal/formly-filter-horizontal.component.html
- libs/documentation/src/lib/storybook/formly/formly-filter/formly-filter-horizontal/formly-filter-horizontal.component.ts
Document fix for the horizontal filters
https://github.com/GSA/sam-design-system/issues/1477
> Horizontal Filter - Allow 'Reset' to clear keyword input

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
> Autocomplete clear text on selection in freetext mode

- libs/documentation/src/lib/storybook/actions/actions-label/actions-label.component.ts
removed shadow from action button.
> remove shadow from action button

- libs/packages/components/src/lib/top-banner/top-banner.component.html
- libs/packages/components/src/lib/top-banner/top-banner.component.ts
This PR is for updating the flag path configurable
https://github.com/GSA/sam-design-system/issues/1509
> Top banner Flag path input added to configure the flag image

- libs/packages/components/package.json
- libs/packages/sam-formly/package.json
- libs/packages/sam-material-extensions/package.json
- package-lock.json
- package.json
> Increment version to 17.0.8

- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
- libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
This PR is for not to clear text from the Input it's a single selection mode
https://github.com/GSA/sam-design-system/issues/1526
> Autocomplete Removed clear text in single selection mode

- libs/documentation/src/lib/storybook/formly/formly-text-area/formly-text-area.stories.ts
added a dropdown option in storybook to give options for size.
> text area dropdown update

- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
Update sdsStepper's `validateStepsOnInit` input to accept an Array of ids for steps to validate. The id to pass in is the same id provided to the sds-step element. Only the steps whose id is contained in the array will be validated onInit.
If an empty array is passed in, it will be treated as if false were passed in.
Booleans passed in will continue to work as they have previously.
Resolves #1515
> Update validateStepsOnInit to allow only selected steps to be validated onInit

- libs/packages/sam-formly/src/lib/formly/types/checkbox.html
- libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
- libs/packages/sam-formly/src/lib/formly/types/input.ts
This Pr is for updating the attr.aria-describedby property to update to read by JAWS for the form controls.
> attr.aria-describedby updated for input, datepicker, checkbox

- libs/packages/sam-formly/src/lib/formly/wrappers/validation.wrapper.ts
This PR to fix the JAWS issue to read the validation message.
https://github.com/GSA/sam-design-system/issues/1540
> 508 Jaws reading validation message dynamically

- libs/packages/components/src/lib/pagination/pagination.component.html
- libs/packages/components/src/lib/pagination/pagination.component.scss
- package-lock.json
Update pagination labels to match latest design.
Update pagination styling to ensure all elements are aligned as shown in the design.
Resolves #1485
> Update Pagination labels to match designs

- libs/documentation/src/lib/storybook/table/table-header-color/table-header-color.component.html
- libs/documentation/src/lib/storybook/table/table-header-color/table-header-color.component.scss
- libs/documentation/src/lib/storybook/table/table-header-color/table-header-color.component.ts
- libs/documentation/src/lib/storybook/table/table-header-color/table-header-color.module.ts
- libs/documentation/src/lib/storybook/table/table.stories.ts
- libs/packages/sam-material-extensions/src/lib/table/table.component.html
- libs/packages/sam-material-extensions/src/lib/table/table.component.scss
- libs/packages/sam-material-extensions/src/lib/table/table.component.ts
- package-lock.json
Add enum for supported header colors
Add input to table component that accepts enum value
Resolves #1521 
Available colors:
Working table example:
> Add input to allow for table header to be colored

- libs/documentation/src/lib/storybook/actions/actions.stories.ts
- libs/packages/components/src/lib/actions-menu/actions-menu.component.html
This Pr is to support the secondary type for the action menu
https://github.com/GSA/sam-design-system/issues/1557
> Action Menu secondary color added

- package.json
> sam-styles version updated

- libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/formly-stepper-advanced.component.ts
- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
- package-lock.json
Update logic in changeStep to handle case where queryParamKey(step that stepper defaults to after loading) is not one of the steps to be validated onInit. Also handles case where queryParamKey is the only step to be validated onInit. Previously in the first condition the queryParamKey step would also be validated on load. For the second condition, the queryParamKey step would not be validated at all.
Follow up to #1515
> 1515 fix add validation

- libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/formly-stepper-advanced.component.html
- libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/formly-stepper-advanced.component.ts
- libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper-advanced/stepper-advanced.service.ts
- libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper.stories.ts
- libs/packages/sam-formly/src/lib/formly-stepper/sds-step.component.html
- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.module.ts
- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
> DON'T MERGE this PR is only for the demo

- libs/documentation/src/lib/storybook/formly/custom/formly-forms/formly-forms.component.ts
- libs/packages/sam-formly/src/lib/formly/types/button.ts
> Formly button class configurable and updated input behavior

- libs/documentation/src/lib/storybook/selection-panel/selection-panel-children/selection-panel-children.config.ts
- libs/packages/components/src/lib/selection-panel/navigation-mode/navigation-mode.component.html
- libs/packages/components/src/lib/selection-panel/navigation-mode/navigation-mode.component.ts
- libs/packages/components/src/lib/side-navigation/model/side-navigation-model.ts
- package-lock.json
- package.json
Added option to sidenav config to allow individual steps to be disabled.
Resolves #1529
> Add option to disable link in side navigation component

- libs/documentation/src/lib/storybook/formly/formly-filter/formly-filter-horizontal/formly-filter-horizontal.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
- libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
- libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
https://github.com/GSA/sam-design-system/issues/1495
> SDS Search for horizontal filter reset 
